### ISSUE TITLE
Save screenshot requires '.png' in the entered filename

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#100]
If I want to save a screenshot I always have to add '.png' to the filename, even though the only supported image format is png and already selected in the list. If I don't add it to the filename no image is saved. This is quite annoying, if one is not aware of this problem.

**Comment by ChristianFeldmann** [comment]
On windows, I can not reproduce this issue. When I just enter 'test' as the file name, the extension '.png' will automatically be added. Actually, Qt supports way more image formats than just PNG. I will add this.

**Comment by ChristianFeldmann** [comment]
I think this works now as expected.
