### ISSUE TITLE
Display of residual and transform coefficients from libde265 not working for streams with 10bit precision

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#101]
I believe it only works for 8bit.

**Comment by ChristianFeldmann** [comment]
Could you provide a bitstream? I don't have one. If not, I could also create one.

**Comment by nolyn** [comment]
[DrivingInCity_2880x1920_30fps_10bit_420pf_QP37.zip](https://github.com/IENT/YUView/files/1207333/DrivingInCity_2880x1920_30fps_10bit_420pf_QP37.zip)

**Comment by ChristianFeldmann** [comment]
Unfortunately this bug was also in the libde265. Updated libde265 and fixed some missing thigs for > 8 bit content.
