### ISSUE TITLE
Not possible to open files on network drives in Windows 10

### ISSUE THREAD

**Issue by paulhiggs** [IENT/YUView#102]
I have YUV files stored on network drives (WD MyCloud NAS) mapped to drive letters in Windows 10. Windows Explorer can navigate these locations, but YUview does not show drive letters.

**Comment by paulhiggs** [comment]
Cannot seem to reproduce today so closing this

**Comment by ChristianFeldmann** [comment]
Ah it healed itself. Perfect :)
