### ISSUE TITLE
Packed mode still not selectable

### ISSUE THREAD

**Issue by ajaybhargav** [IENT/YUView#103]
I am not able to select packed mode, checked on windows and Linux both with latest release. This was already mentioned in issue #96 which is already closed and marked fixed, But issue remains in latest release.

**Comment by ChristianFeldmann** [comment]
Hi! You are right. This was fixed in the development branch but never merged to the master branch. Sorry about that. I opened a pull request for the changes and when the final tests have passed, we can merge this to the master branch.

**Comment by ChristianFeldmann** [comment]
This was finally merged to the main branch. Enjoy!
