### ISSUE TITLE
Display of Residual might be erroneous

### ISSUE THREAD

**Issue by JensAc** [IENT/YUView#106]
Looking at x = 185, y = 0 in the attached stream. 
YUView / libde265 says:
Residual = -128
Prediction = 173
Reconstruction = 39
Now, shouldn't Reconstruction = Prediction + Residual hold true? 
173 -128 = 45 n.e. 39.
I have also inverse transformed the block yielding Residual = -134 which seems to be correct. 
Am I missing something (Loop filtering, SAO or something else) or is there another bug?

[Traffic_L0_1280x800_30_encoder+intra+main+A+2x_FTBE9_IBD08_IBD18_IBD08_IBD18_QPL1034_SEIDPH0.shvc.zip](https://github.com/IENT/YUView/files/1317673/Traffic_L0_1280x800_30_encoder.intra.main.A.2x_FTBE9_IBD08_IBD18_IBD08_IBD18_QPL1034_SEIDPH0.shvc.zip)

**Comment by ChristianFeldmann** [comment]
Actually there is more internal stuff happening:
  - The residual signal is read from libde265 using an 8 bit value. So -128 is the lowest possible value and was clipped to 8 bit. The real residual value might have been even lower (maybe it was -134)
  - Loop filtering and SAO is applied for the reconstruction so the following holds true: Reconstruction = Filtered(prediction + residual)

**Comment by JensAc** [comment]
Thanks for the clarification. I am closing this. If you see room for improvement, reopen it and I will take a deeper look into this.
