### ISSUE TITLE
Synchronous Playout for Side By Side View

### ISSUE THREAD

**Issue by aachenmax** [IENT/YUView#11]
When two videos are selected and played out in the side-by-side mode, they are not perfectly in sync. This is especially noticable at very low frame rates and when sequences are loaded into the cache for the first time. 

Changing to synchronous playback might be hard to achieve since that requires more low level access to the rendering/drawing/updating queue. It might not even possible at all. A quick fix would be to add another "synchronous playback mode", where two frames are just combined into a single pixmap which is displayed in a single widget.

**Comment by fjaeger** [comment]
Does it help to use a QtOpenGLView as the base class for the DisplayWidgets?

**Comment by fjaeger** [comment]
Have you tried whether using "update()" instead of "repaint()" in DisplayWidget's drawFrame() method improves the situation?

**Comment by aachenmax** [comment]
maybe fixed by using update()
