### ISSUE TITLE
Packed modes not selectable in released build 

### ISSUE THREAD

**Issue by jonathanlester** [IENT/YUView#112]
Similar to issue #103 and #96. The released build (source from here https://github.com/IENT/YUView/releases as well as the Ubuntu version) won't let you decode an image with a packed format. I thought my image was the problem until I found the issue and noticed that the "YUV Format" dropdown never changed from "4:2:2 8-bit" to a packed mode. 

Downloaded and built the development and master branches and it works fine. Might be worth adding a note on the project pages in case someone needs that specific feature. Works great once I figured this out though.

**Comment by ChristianFeldmann** [comment]
Hi! Thanks for the report. So the release build has the bug, but when you download the master branch, the bug is fixed? This seems strange since the release version should always be the latest version of the master branch... As I see I fixed this in #103 and it was merged to the master branch. @aachenmax did something go wrong with the release?

**Comment by aachenmax** [comment]
@jonathanlester Could you tell us the build information for the compiled release version that gave this error? It is shown in the Help->About YUView section.
@ChristianFeldmann The last release build for Windows was definitely the one matching the last commit in the master branch from 22.09.2017. Both the autoupdate and installer were updated successfully according to the logs. We could of course trigger a rebuild just to be sure?!

**Comment by ChristianFeldmann** [comment]
Now I see. I added a comment to the release. 
Just on a side note: You are getting YUView Version 0 because you are probably not using git to checkout the release. When you just download the source as a .zip file, YUView does not know what the version of the source is (it uses git to find out).
