### ISSUE TITLE
Problem with chroma resampling for 420, 10bit content

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#117]
At sharp horizontal edges color is not not displayed correctly. I believe the bug is in UVPlaneResamplingChromaOffset, since commenting its call will remove the edges, but it will also display the color completely wrong. Still looking for the exact source.

![example2](https://user-images.githubusercontent.com/5878536/39024511-b4997dba-4441-11e8-92b7-e9e3e81ee6af.png)
![example1](https://user-images.githubusercontent.com/5878536/39024512-b4c0701e-4441-11e8-8d5d-25dc3c4caf95.png)

**Comment by ChristianFeldmann** [comment]
We just discussed this: I think this is not a bug. It depends on the specification of you YUV format. By default we assume a Y-offset for the chroma component of 1/2. If this is not true for your YUV format, you can freely configure this in the custom YUV format dialog.
