### ISSUE TITLE
Issue with .y410 files

### ISSUE THREAD

**Issue by zplov** [IENT/YUView#118]
I think there is a problem when i try to view .y410 files.    From msdn, y410 should be 4:4:4 Packed 10bit, but when selecting this in YUView, the picture is not showing correctly.   

Other raw picture viewers are recognize y410 and displaying it correctly.

**Comment by ChristianFeldmann** [comment]
Hi, thank you for spotting this. It seems like the Y410 format has a rather unusual packed layout with two alpha bits followed by 10 U, 10 Y and 10 V bits (32 bits total per pixel). It would be really helpful if you could provide a file in this format so I can add the format and test it.

**Comment by ChristianFeldmann** [comment]
I will close this for now. @zplov please reopen when you can provide a test file.

**Comment by ValZapod** [comment]
> support for this in ffmpeg so I can not generate a test file.

https://github.com/zcwang/ffmpeg-patchset_2020Q4/blob/a2ef5754cf816a803caacabed6880e40691b26cd/0001-lavu-pixfmt-add-new-pixel-format-0yuv-y410.patch

https://github.com/zcwang/ffmpeg-patchset_2020Q4/blob/a2ef5754cf816a803caacabed6880e40691b26cd/0002-swscale-Add-swscale-and-fate-support-for-0YUV.patch

**Comment by uartie** [comment]
https://github.com/FFmpeg/FFmpeg/blob/3d1597d3e2ff9a6625af23be63131142a910d403/libavutil/pixfmt.h#L414-L415
