### ISSUE TITLE
rescaling problems

### ISSUE THREAD

**Issue by Graphic9** [IENT/YUView#119]
when rescaling the size of video frame,  the frame image doesn't appear in the middle of screen.

**Comment by ChristianFeldmann** [comment]
Hi,
could you please elaborate on what you mean? How did you zoom (Keyboard/Mouse wheel)? What did you expect to happen? Note that when zooming in using the mouse wheel, the center position of the zoom is the mouse pointer position (the position of the image that you are pointing at will be at the same position after the zoom). You can disable this in the settings.

**Comment by ChristianFeldmann** [comment]
Closing for now. Please re-open if needed.
