### ISSUE TITLE
Display of UV values incorrect for YVU(IL) 4:2:2 10-bit

### ISSUE THREAD

**Issue by S-Fe** [IENT/YUView#120]
When zoomed in on a frame for a file in YVU(IL) 4:2:2 10-bit format, the numerical values shown against the pixels appear to assume the the data is in 3-planar mode (at least, when I look at the file data with a hex editor this seems to be the case)

Further, If you toggle between, say  YVU(IL) 4:2:2 10-bit  and YVU 4:2:2 10-bit, the image colours change as expected but the numerical values stay constant. 

I've only tested 10-bit data - it might have the same bug with other bit depths.

**Comment by ChristianFeldmann** [comment]
Hi thanks for reporting this. Could you provide a YUV file so that I can test this? With (IL) you are referring to Interleaved U/V planes, right?

**Comment by S-Fe** [comment]
Yes, IL=>interleaved.  I'd need to manufacture an image as I don't have the rights to share the image/video that flagged up the problem....

Actually, I just realised you don't need one.  If you were to open, say, any 3-plane video/image (and FWIW the bug also seems to exist for other formats, e.g. YUV 4:2:0 8-bit), zoom in so you can see the Y/U/V numeric values, and then customise the YUV format to interleaved, you'll see all the pixel colours change but the numbers will remain the same.

**Comment by ChristianFeldmann** [comment]
Perfect thank you for the description. I can reproduce the bug.

**Comment by ChristianFeldmann** [comment]
Fixed in the development branch. The YUV handler pixelValue function did not understand UVinterleaved files.
