### ISSUE TITLE
Providing FFMpeg shared binaries to YUVView on Windows

### ISSUE THREAD

**Issue by ramanarvind** [IENT/YUView#125]
Hi, 
I am trying to provide FFmpeg shared binaries (dlls) to YUVView but am unable to do so. I placed shared binaries from the v4.0.1 of FFmpeg inside the folder "C:\Program Files\YUView\ffmpeg" but YUVView failed to open a MP4 file. I tried placing both 32 bit and 64 bit binaries inside the "C:\Program Files\YUView\ffmpeg" folder. 

I also tried to specify the location of the FFmpeg DLLs as shown in the attached screenshot but that too throws an error. 

I suspect YUVView requires older shared library DLLs, however, I could not find which version of the FFmpeg DLLs is YUVView compatible with. Would really appreciate any help you may be able to provide in helping me get YUVView to work with FFmpeg. 

Best regards
Arvind
![capture](https://user-images.githubusercontent.com/1332983/43157927-fea143d4-8f9b-11e8-9812-30d72a578cce.JPG)

**Comment by ChristianFeldmann** [comment]
Hi,
yes it could be that the version you are using does not support ffmpeg 4 yet. I have only (very) recently added support for ffmpeg 4 in the new_compressed_file_reading branch. Are you using this branch? If not this might be worth a try.

**Comment by ramanarvind** [comment]
Thanks for the prompt response. No, I was not using the new_compressed_file_reading branch. 
I tried working with 3.4.2 version of the FFmpeg shared DLLs (https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-3.4.2-win64-shared.zip) and that worked seamlessly. I can't thank you enough for making this tool. I am going to recommend my team to give this a try.
