### ISSUE TITLE
Difference sequence raw rgb bug

### ISSUE THREAD

**Issue by gregc-91** [IENT/YUView#126]
Loading two raw RGB 8bit (interleaved, though untested on planar) files and adding a difference sequence does not seem to work.

The difference sequence gives a flat gray output, even when amplifying differences by 10.
The info window reports an MSE of 0, despite there being visible differences in the two files in the sequence.
File 1 and File 2 in the info window display the correct filenames for the two different files.
Selecting "Mark differences" displays "Frames are identical" in the Info window.

This feature works as expected for YUV files so I believe I have the correct procedure.

I've tested with both the precompiled binaries and compiled from the latest source with the same results.

**Comment by ChristianFeldmann** [comment]
Thanks for spotting this. We always work in the YUV domain so this was probably just never tested :)
Fixed in the develop branch which will be merged very soon.
