### ISSUE TITLE
Error parsing the Y4M header: Could not locate the next 'Frame' indicator

### ISSUE THREAD

**Issue by luofalei** [IENT/YUView#130]
Enviroment: Windows 10
Version: 2.0-194-gd0268d6

Sequence `aspen` downloaded from:
https://media.xiph.org/video/derf/
https://xiph-media.net/video/derf/y4m/aspen_1080p.y4m

**Comment by ChristianFeldmann** [comment]
Hi! Which branch did you use? Or do you use the master version that we provide binaries for?
In the development branch your file works. We will merge / deploy the development branch into the master very shortly. Stay tuned :smile:

**Comment by ChristianFeldmann** [comment]
We just updated the master branch (and the deployed version). Maybe you can retry using this version.

**Comment by luofalei** [comment]
It works well now.
