### ISSUE TITLE
FFMPEG Integration on Windows doesn't Work

### ISSUE THREAD

**Issue by arndtc** [IENT/YUView#131]
On Windows 10, I downloaded the latest version of YUView (Version 2.0-194-gd0268d6).  Then I downloaded the ffmpeg-4.0.2-win64-shared.zip and tried to integrate it with YUView and if failed.

Every file I try to open that isn't a YUV file say that the ffmpeg libraries can't be found.

When I try to point to the specific libraries in the setting I get an error.

`The selected file does not appear to be a usable ffmpeg avFormat library. Error:`

**Comment by ChristianFeldmann** [comment]
The new ffmpeg interface of version 4 is not supported in the main and development branch yet. I am working on an integration in the new_compressed_file_reading branch but this is not completed yet. For now you can either try the new branch with ffmpeg 4 or you will have to use an older version of ffmpeg (like 3.4).

**Comment by arndtc** [comment]
Thanks for the quick reply.  I was able to find ffmpeg-3.4.2-win64-shared.zip and that got me past the FFMPEG error.

But then when I tried to load flv, mp4 and 264 files unfortunately I kept getting the below error.  But these files did play fine with ffplay.exe.
```
There was an error opening the file:
Error scanning bitstream for key pictures.
```

**Comment by ChristianFeldmann** [comment]
Hi I just tested ffmpeg 3.4.2 with the latest master windows build. I was able to open an mp4 file. I did not test all different file types. Possibly there is something wrong with the handling of other file types. If you can provide me with a link, I can try to test it on my platform.
As I said the implementation of ffmpeg is under heavy improvement right now :)

**Comment by arndtc** [comment]
Just tried the latest installer v2.1 (Version 2.0-423-g9f83e19 in the help about.) and I'm able to use the latest [ffmpeg-4.0.2-win64-shared.zip](https://ffmpeg.zeranoe.com/builds/).  Thanks for fixing this so quickly.
