### ISSUE TITLE
Virus warning for windows installer

### ISSUE THREAD

**Issue by Skypr** [IENT/YUView#142]
I just tried to install the viewer on my Windows 10 machine, only to find out that Windows defender flagged the file as containing a trojan. 
Scanning it with [virustotal resulted in 2/65 scanners finding something](https://www.virustotal.com/de/file/533713a5f45d66d9d3d4bc88f3e5a4cdcd14df7c58cd48983af5ac59199d7a4f/analysis/1535803330/)

**Comment by ChristianFeldmann** [comment]
That is really strange. It seems to be the windows defender that tags it as "trojan detected". This must have changed recently because I downloaded and installed it using the installer from our page.

**Comment by aachenmax** [comment]
I am a bit puzzled to be honest, why the installer now got flagged and how we can resolve this issue. @Skypr  do you maybe have any further details what exactly could have triggered this false positive?

**Comment by ChristianFeldmann** [comment]
I built a new installer manually (without openSSL) and it als reports a trojan.
https://www.virustotal.com/de/file/c6738fc9c02210df896d3671715f3ae583bd0ef41c480320c371f84504a1fb21/analysis/1536356524/

**Comment by Skypr** [comment]
Have you tried packaging a small hello world program into an installer?

**Comment by ChristianFeldmann** [comment]
Yep that seems to be it. I created an installer which only installs the versioninfo.txt file:
https://www.virustotal.com/de/file/fab49276c7f6e252d19034cdc39bc33ef2444546b1f2974210575abfce4adebe/analysis/1536392128/

**Comment by ChristianFeldmann** [comment]
I created som wix scripts to create an .msi installer. So far, it's a very simple one but it could be further extended. I guess we just need to adapt the deployment scripts a little bit to make everything automatic. @aachenmax 🙂

**Comment by aachenmax** [comment]
@ChristianFeldmann heat, light and candle, looks great :) 👍 I will change the deployment accordingly

**Comment by arndtc** [comment]
I saw this as well.  I just zipped it up and then unzipped it and ran the installer and it stopped giving the warning.
