### ISSUE TITLE
Release v2.1 Windows install - Help about says Version 2.0-423-g9f83e19

### ISSUE THREAD

**Issue by arndtc** [IENT/YUView#147]
I just downloaded an installed [Release v2.1](https://github.com/IENT/YUView/releases/tag/2.1) on Windows and the help about says that it is Version 2.0-423-g9f83e19.

**Comment by ChristianFeldmann** [comment]
Yes that probably happened because we tagged the merge after the merge to the master branch so that the appveyor build did not know about the release tag yet. This will auto-fix in any future merge/release.
