### ISSUE TITLE
setup error for ffmpeg libraries

### ISSUE THREAD

**Issue by pengbins** [IENT/YUView#158]
![image](https://user-images.githubusercontent.com/1439218/48887168-44ea9080-ee69-11e8-92f0-333a035d4b2b.png)

Windows 10,

ffmpeg-4.1-win64-shared.zip

**Comment by pengbins** [comment]
It seems  only avcodec major version <= 57 is supported. 

So can't use the latest ffmpeg(4.1), but ffmpeg-3.4.2-win64-shared.zip works.

**Comment by ChristianFeldmann** [comment]
Yes support for ffmpeg 4 was added in the development branch but did not get into the master branch yet. We will have to do another merge of this branch soon. If you want to test the development branch (with support for ffmpeg 4 and many more features) you can find the windows installation files in appveyor: [Appveyor](https://ci.appveyor.com/project/aachenmax/yuview/builds/20265037/artifacts)
