### ISSUE TITLE
[Suggestion] Refine the error messages for unsupported ffmpeg libraries

### ISSUE THREAD

**Issue by pengbins** [IENT/YUView#159]
In issue #158 , the setup error message reported for unsupported ffmpeg 4 is very confusing.

The message said the major version returned is different than it's file name indicates, which is not true.

Maybe the message need to change to tell user this version of ffmpeg is not supported.

**Comment by ChristianFeldmann** [comment]
Absolutely. I am already working in this in the branch debug/ffmpegLoading

**Comment by ChristianFeldmann** [comment]
Ok this is done. YUView now gives a nice log with what was tried and what failed.
