### ISSUE TITLE
Segmentation fault, Qt 5.12.1

### ISSUE THREAD

**Issue by venkatesh369** [IENT/YUView#166]
Hello. I am getting segmentation fault when I try to build YUView on my system which has QT 5.12.1. Could you please help me in solving this.

**Comment by nolyn** [comment]
Hi. I do not have any problem building with Qt 5.12.1-2 on Arch Linux using the master branch

**Comment by venkatesh369** [comment]
Hi,

After building were you able to open hevc stream contained in .mp4
container?

Regards
Vj

**Comment by ChristianFeldmann** [comment]
In order to open mp4 containers you will need to have ffmpeg installed (and possibly set tell YUView where the ffmpeg libraries are). When does the segemntation fault occur? When opening the hevc file? You could try to used the development branch which has some non-released fixes.

**Comment by venkatesh369** [comment]
Hello I am trying to build YUView using QtCreator. I was successful in
building it and running it (release mode) for mp4 files that have X264
stream. I am experiencing crash only for mp4 files with HEVC streams alone.

I am giving out put of QtCreator in case this has more information.

qt5ct: using qt5ct plugin

qt5ct: D-Bus global menu: no

QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once
QUrl("https://api.github.com/repos/IENT/YUView/commits")

ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 pid=5185 comm="YUView"
exe="/home/vj/Dropbox/Marios_Shared/PhD/slignshot/YUView_Lin/build-YUView-SystemGCC_x64-Release/build/release/YUView"
sig=11 res=1

13:20:56: The program has unexpectedly finished.

13:20:56: The process was ended forcefully.

13:20:56:
/home/vj/Dropbox/Marios_Shared/PhD/slignshot/YUView_Lin/build-YUView-SystemGCC_x64-Release/build/release/YUView
crashed.

**Comment by nolyn** [comment]
I can open and playback hevc streams contained in mp4 containers.

**Comment by ChristianFeldmann** [comment]
From your comments I see that you are on Linux. What YUView branch did you checkout? If you did not try this yet, you can give the development branch a try.
The problem can arise if the libde265 decoder (which is the default HEVC decoder) is not installed / can not be found. In the YUView settings you can set a manual path to the libde265.so file (you can download a precompiled version from [here](https://github.com/ChristianFeldmann/libde265/releases). Alternatively you can try to set the default HEVC decoder to use ffmpeg.

**Comment by venkatesh369** [comment]
Hello,

I compiled libde265 from source and now I have the Release working. Thanks
for all the support.

PS: I had to add 2 more header files to get YUView running on Debian
Streatch. It has Qt 5.7 with gcc 6.3.0.
1. #include <cassert>
a. parserCommon.cpp
b.
2. #include <QUrlQuery>
a. playlistItemImageFile.cpp
b. playlistItemImageFileSequence.cpp
c. playlistItemStatisticsFile.cpp

I am still trying to get compilation work with Windows using Qt-Creator.

Regards
Vj

**Comment by ChristianFeldmann** [comment]
Ok nice to hear that it seems to be working now. Also nice to hear that it compiles with Qt 5.7. as well. Did you also try the precompiled libde265 libraries as well? Since libde265 has no external dependencies this should work on any x64 platform out of the box. 
I just tested Qt.5.12.1 on windows and everything compiles as expected. I guess we can close this issue then.

**Comment by venkatesh369** [comment]
HI yes

I was able to compile in Windows also. My major problem is that I have
anaconda installed and it is set as the major qt  environment in windows.

It took me some time to figure it out but now I get it working in release
with visual studio 2015.

Thank you for your support.

Also is there any channel that I can join where I can ask questions about
YUView? I would like to use the source code for my research.

Regards
Vj

**Comment by ChristianFeldmann** [comment]
:+1:
