### ISSUE TITLE
YUView Crash / Segfault when changing bitdepth

### ISSUE THREAD

**Issue by aachenmax** [IENT/YUView#175]
The issue is the following:
- Caching enabled
- Load a large raw 10-bit 420 YUV file, which was erroneously detected as 8-bit
- Change the bit depth at the YUV File Properties widget to 420 10-bit LE
--> Crash

I tracked the origin to the following line and believe this is the reason:
--> Segfault occurs during convertYUVPlanarToRGB(sourceBuffer, outputImage.bits(), curFrameSize, yuvFormat);
I am assuming that this happens because sourceBuffer was not reloaded with the 10-bit data. This (probably) happens because for the caching item, loadRawYUVData(frameIndex) is not being performed. It appears that currentFrameRawData_frameIdx was not correctly invalidated and so the following happens, which should not happen:

  if (currentFrameRawData_frameIdx == frameIndex)
    // Buffer already up to date
    return true; 

Edit: this is also a relevant issue on the master branch

**Comment by ChristianFeldmann** [comment]
@aachenmax  Does your fix fix this issue? Then wen can close this :)
