### ISSUE TITLE
Add Playlist support for Difference Objects

### ISSUE THREAD

**Issue by aachenmax** [IENT/YUView#18]
Right now Difference Objects are not exported into Playlists.
Note that also the existence of StatisticsObjects needs to be checked:
A full tree (worst case) would look like that
-DifferenceObject
--|--StatsObject1
--|--FrameObject1
----|--StatsObject2
--|--FrameObject2
----|--StatsObject3

**Comment by ChristianFeldmann** [comment]
This should work with the new layer. All kinds of nested structures are allowed.
