### ISSUE TITLE
[Feature] Add the name of the file in the diff view

### ISSUE THREAD

**Issue by grandemk** [IENT/YUView#180]
It can be difficult to know which file is on which side in the diff view (it depends on which one was added last)
A good thing would be to add the file name on top of the images to identify them.
In comparison view, the name could be on each side of the bar.

**Comment by ChristianFeldmann** [comment]
Yap that is a very good Idea. Basically it depends on the order in which you selected the items. The first selection is on the left and the second is on the right. This is not really intuitive though. 
So we could render the file name at the top in a small overlay. Points to answer are:

**Comment by grandemk** [comment]
I think you are right, it can get in the way too, so there should be a switch to hide / show like the rest of the UI.

I think you don't really need the whole path (as they can become very long as people use them to encode some properties of the yuv being diffed).

I think what you want to show is something that differentiate the two files.
I would find the first path part (directory or the filename) diffing and I would only keep the name from there.

A random example:
../../../../1920x1080/test1/L3xS3xV1/filename.yuv
../../../../1920x1080/test1/L3xS2xV1/filename.yuv
would become:
L3xS3xV1/filename.yuv vs L3xS2xV1/filename.yuv

**Comment by ChristianFeldmann** [comment]
That sounds nice. An even smarter way to approach this 👍

**Comment by ChristianFeldmann** [comment]
Ok this is added. It is available in the develop branch. Give it a test ride and please let me know if it does not work in some specific cases :)

**Comment by AllegroDvt** [comment]
I gave it a test ride, I've fixed the issues I encountered, see pull request #183.
Thanks for the quick implementation :)

**Comment by grandemk** [comment]
I gave it a test ride, I've fixed the issues I encountered, see pull request #183.
Thanks for the quick implementation :)
