### ISSUE TITLE
Links for builders on http://ient.github.io/YUView/ broken

### ISSUE THREAD

**Issue by mwiflms** [IENT/YUView#186]
It seems that the links on that page need to be updated.

- Windows: https://github.com/IENT/YUViewReleases/blob/master/win/installers/SetupYUView.exe?raw=true should be changed to https://github.com/IENT/YUViewReleases/blob/master/win/installers/YUViewSetup.msi?raw=true
- Mac: https://github.com/IENT/YUViewReleases/blob/master/mac/YUView.zip?raw=true should be changed to https://github.com/IENT/YUViewReleases/blob/master/mac/YUView-MacOs.zip?raw=true

**Comment by ChristianFeldmann** [comment]
Thanks for the hint. I updated the links. It ca take a day for GH to update the actual page.

**Comment by ChristianFeldmann** [comment]
OK it just took a few seconds 😆
