### ISSUE TITLE
Can't open any file

### ISSUE THREAD

**Issue by tyeeman** [IENT/YUView#188]
Just installed and trying to open a basic h264 file and it can't. Do I have to download ffmpeg separately?

**Comment by ChristianFeldmann** [comment]
Hi!
For legal reasons, YUView does not ship with a native h.264 decoder. So YUView relies on ffmpeg for decoding of h.264 video which must be installed seperately. How this works depends on the platform that you are on. Please see https://github.com/IENT/YUView/wiki/FFmpeg

**Comment by ChristianFeldmann** [comment]
I hope this woked/helped. If not please let me know. However, this is not an issue to perform any work on. If you are of a different oppinion, please reopen.
