### ISSUE TITLE
The quality of UI is bad. not support retina

### ISSUE THREAD

**Issue by doyee** [IENT/YUView#194]
Thanks for YUView, it is great product, Can you support retina on Mac.

**Comment by ChristianFeldmann** [comment]
What exactly is bad? Some more detail would help. Or a screenshot would be great. 
Unfortunately we are just relying on Qt to render the UI in a usabel way and we don't have much control over it in all situations. What you could try is a newer version of Qt. They are constantly fixing things for HDPI displays. I built one version which will be released shortly with a newer Qt version. You could give this a try: https://github.com/IENT/YUView/releases/download/test3/YUView-MacOs.zip

**Comment by doyee** [comment]
<img width="822" alt="Screen Shot 2019-11-21 at 12 22 26 PM" src="https://user-images.githubusercontent.com/2289290/69378880-25489c80-0c64-11ea-90b7-32dc803f22e3.png">

still bad

**Comment by doyee** [comment]
<img width="1103" alt="Screen Shot 2019-11-21 at 1 36 41 PM" src="https://user-images.githubusercontent.com/2289290/69378936-44472e80-0c64-11ea-90f9-2651644f8c95.png">

the quality is still bad

**Comment by doyee** [comment]
please check the text aliasing

**Comment by ChristianFeldmann** [comment]
Fixed.
