### ISSUE TITLE
Try to guess the width height

### ISSUE THREAD

**Issue by doyee** [IENT/YUView#196]
try to guess the resolution if  widthxheight  as part of fileName. it is very useful for image engineer just like me.

thanks.

**Comment by doyee** [comment]
IMG_1514807568046_0_4000X1824_org_[1]1000000_V1321005_OWR(0,0,4000,1834).NV21

the resolution is 4000X1824

**Comment by doyee** [comment]
it is common action that resolution as part of fileName

**Comment by ChristianFeldmann** [comment]
YUView is able to detect the format (resolution and raw format) from the filename. However, not all different ways of writing it are implemented. In your case, using a non-capital X should already do the trick. So if the filename contains a "_4000x1824_" (notice the non capital x), this should work. But a capital X should also work. I will add this.

**Comment by ChristianFeldmann** [comment]
I added the ability to also detect the capital X in a resolution string so I will close this issue for now. Please re-open if anythong else is missing.
