### ISSUE TITLE
Doesn't support quantization selection for RGB pixel format

### ISSUE THREAD

**Issue by hizukiayaka** [IENT/YUView#199]
There are both narrow and full range RGB(in GPU) encoding exits. And RGB pixel format may use a different white point.

**Comment by ChristianFeldmann** [comment]
Hi thanks for your report. Although I don't quite understand what you mean. So you are saying there also is a limited range RGB format like the Mpeg/limited YUV formats? Do you have any documentation on this? I would be really interested to read more about it. 
And secondly: What exactly is your issue with YUView in this case? Is anything not being shown correctly? Do you think the conversion to the display RGB colorspace should be changed? If yes, how?

**Comment by hizukiayaka** [comment]
@ChristianFeldmann 
You have look here
http://avisynth.nl/index.php/Color_conversions
For example the sRGB would be limitted range usually.

**Comment by ChristianFeldmann** [comment]
Ah ok I did not know that but it makes sense that there is a  similar limited range RGB format for the analoge standards linke sRGB. I understand. But my question remains:
 - What exactly is your problem with YUView? The currentl implementation will just display the RGB values on screen as they are. If the input is of range [16...235] then the displayed values will also be. If the RGB values are full range, they will also be shown as full range. Do you think the linited range [16...235] should be scaled to the full range for display? Are you seeing any visual issues with the current implementation?

**Comment by hizukiayaka** [comment]
> 
> 
> Ah ok I did not know that but it makes sense that there is a similar limited range RGB format for the analoge standards linke sRGB. I understand. But my question remains:
> 
Well, OpenGL ES still support sRGB Surface
>     * What exactly is your problem with YUView? The currentl implementation will just display the RGB values on screen as they are. If the input is of range [16...235] then the displayed values will also be. If the RGB values are full range, they will also be shown as full range. Do you think the linited range [16...235] should be scaled to the full range for display? Are you seeing any visual issues with the current implementation?
It depends on the graphics driver behavior. Nvidia platform would have such problem.
For example, [128, 128, 128] would present a different color in full or limited range.

**Comment by ChristianFeldmann** [comment]
Ok but are you seeing any colors being displayed wrong? YUView does not have any connection to graphics drivers. As a matter of fact we currently don't even use openGL for drawing (at least not directly). We just convert the images to RGB into QPixmas and draw them using the QPainter framework.

**Comment by hizukiayaka** [comment]
Of course it would be wrong. A limited range RGB image been regarded as full range would looks more light than it should be, in reverse a full range RGB image been regarded as limited range would lose more detail.

**Comment by ChristianFeldmann** [comment]
Added
