### ISSUE TITLE
QSize header include missing from fileSource.h

### ISSUE THREAD

**Issue by ian-arkver** [IENT/YUView#209]
Hi,

Compiling version 2.4 (id: d6dd423) I get errors about QSize being an incomplete type for frameSize.

```
src/filesource/fileSource.h:80:11: error: field ‘frameSize’ has incomplete type ‘QSize’
   80 |     QSize frameSize;
      |           ^~~~~~~~~
```
Adding a #include fixes it and allows compilation to complete. Fwiw, this is with Qt 5.14.0 on Manjaro Linux. Trivial diff below, fyi.

Regards,
Ian
```
diff --git a/YUViewLib/src/filesource/fileSource.h b/YUViewLib/src/filesource/fileSource.h
index 4177c3d7..3cb7af70 100644
--- a/YUViewLib/src/filesource/fileSource.h
+++ b/YUViewLib/src/filesource/fileSource.h
@@ -38,6 +38,7 @@
 #include <QFileSystemWatcher>
 #include <QMutex>
 #include <QMutexLocker>
+#include <QSize>
 #include <QString>
 
 #include "common/fileInfo.h"
```

**Comment by ChristianFeldmann** [comment]
Hi thanks for the report. Yes it depends on your compiler/platform/QTVersion what the compiler actually does so this can happen. 
Just to make sure: Which branch are you compiling? Is it the current master branch?

**Comment by ian-arkver** [comment]
Yeah, master branch at the commit mentioned above with gcc 9.2.0.
Does adding the #include break any platform? I'd have thought not, but I'm not that familiar with Qt.

**Comment by ChristianFeldmann** [comment]
Ok perfect. No adding QSize as another include should not break anything.

**Comment by ChristianFeldmann** [comment]
Added it in develop.

**Comment by ian-arkver** [comment]
Thanks. Nice utility, btw. Came here because Manjaro lib updates broke vooya again, but YUView seems excellent so far.

**Comment by ChristianFeldmann** [comment]
Thank you. Spread the word :)
