### ISSUE TITLE
development branch: Performance analysis

### ISSUE THREAD

**Issue by ChristianFeldmann** [IENT/YUView#21]
I dit a test with the conversion performance. On my maschine, the following times were measured:
Resolution 1920x1080 YUV 420
Loading: 1ms
420->444: 1 ms
YUVMath: 2 ms (if activated)
444->RGB: 4 ms
conversion to pixmap: 4ms
drawing the pixmap: 1-4 ms

**Comment by nolyn** [comment]
which resolution?

**Comment by nolyn** [comment]
My machine is much slower apparently (i5-5200U CPU @ 2.20GHz).

Hab nur 420 getestet.

1920x1080:
420->444: 10-13ms
YUVMath: 8-13 ms
444->RGB: 7-9 ms
QPixmap: 4-11 ms

2560x1600:
420->444: 19-21ms
YUVMath: 16-20 ms
444->RGB: 11-15 ms
QPixmap: 14-34 ms

**Comment by nolyn** [comment]
so, nun meine ergebnisse mit development_performanceTest:

1920x1080 8bit:
Loading: 0 ms
420->444: 1 ms
YUVMath: 4 ms (if activated)
444->RGB: 4 ms
conversion to pixmap: 1 ms

2560x1600 8bit:
Loading: 1 ms
420->444: 2 ms
YUVMath: 8 ms (if activated)
444->RGB: 9 ms
conversion to pixmap: 2 ms

**Comment by aachenmax** [comment]
MinGW 64bit with all that it can do:
-O3 -Ofast -msse4.1 -mssse3 -msse3 -msse2 -msse -mfpmath=sse

1920x1080 8bit: 
Loading: 0 ms 
420->444: 1 ms 
YUVMath: 7 ms (if activated) 
444->RGB: 4 ms 
Conversion to Pixmap: 6 ms

2560x1600 8bit: 
Loading: 1 ms 
420->444: 2 ms 
YUVMath: 15 ms (if activated) 
444->RGB: 9 ms 
Conversion to Pixmap: 13 ms

**Comment by ChristianFeldmann** [comment]
I added some performance testing tools (interprete the results with caution). This could be further extended.
