### ISSUE TITLE
Detecting "packed" formats from file name

### ISSUE THREAD

**Issue by ulfzie** [IENT/YUView#211]
Hi, 

I have an issue to set "packed" mode with the file name.
My needed parameters for YUV are:
Resolution: 1280*720
Bit depth: 16
Chroma subsampling: 444
Endian: little endian
Packed in "YUV" order.

This is the used file name:
example_1280x720_16bit_444_yuv16le_packed.yuv

The "packed" keyword is not recognized. If I tick the "Packed" checkbox evrything is fine.
Tested with 2.4

Can you help? 
Ulf

**Comment by ChristianFeldmann** [comment]
Hi! 

Yes detecting the packed format from the filename is not implemented. This definitely could be added.

**Comment by ulfzie** [comment]
Hi,

I have seen a refernce in the regexp in videoHandlerYUV.cpp . But this not called for yuv images.

Would be cool if you can add this.

Thanks,
Ulf

**Comment by ChristianFeldmann** [comment]
Yep this was not too hard and I added it. I just need to test it.

**Comment by ChristianFeldmann** [comment]
Ok I just looked if I have a packed example or if ffmpeg could generate one but I don't think it can generate packed YUV 444 for me. Could you send me an example file so I can check if it works as expected?

**Comment by ulfzie** [comment]
Here you go: 
[sample_1280x720_16b_yuv16le_packed_20200109_114812.zip](https://github.com/IENT/YUView/files/4039995/sample_1280x720_16b_yuv16le_packed_20200109_114812.zip)

**Comment by ChristianFeldmann** [comment]
It works! And thank you for the easteregg in the example. 😆 👍

**Comment by ChristianFeldmann** [comment]
Done!

**Comment by ulfzie** [comment]
Hi Christian,

is used this filename: "sample_file_1280x720_16b_yuv16le_packed_20200109_114812.yuv"
If would expect to have this setting:

![grafik](https://user-images.githubusercontent.com/55350205/72729350-4445ab00-3b8f-11ea-9fad-dc2588fc16c6.png)

Unfortunately I get this:
![grafik](https://user-images.githubusercontent.com/55350205/72729418-69d2b480-3b8f-11ea-9602-3b71c0f4cf31.png)

I set a breakpoint at fileSource.cpp, line 279: format.packed = true;
This is hit.

I used Version 2.4-5-g5663936b on Windows for testing.

Best regards,
Ulf

**Comment by ChristianFeldmann** [comment]
Hi!

I think this might be as simple as a wrong version. The commit you used was not the final one that I merged. Could you update to the latest commit from the development branch and check again?

**Comment by ulfzie** [comment]
Hi Christian,

I just tested with the Windows release version 2.6 . If I use the provided sample it is not working. Can you please check? Do I use the wrong name convention?

Thanks,
Ulf

**Comment by ChristianFeldmann** [comment]
Thanks for the report. Yes this really does not seem to work. Will debug it.

**Comment by ChristianFeldmann** [comment]
sample_1280x720_16bit_444_packed_20200109_114812.yuv
