### ISSUE TITLE
Problems with imageformat 438x246 4:2:0 8 bit planar

### ISSUE THREAD

**Issue by gnobbi** [IENT/YUView#22]
## Hello,
i got problems with a specific image format 438x246 4:2:0 8 bit  I do not know why especially this format, but as shown in capture1 its shifted every row. I opened the same file with an another yuv viewer and it works fine see capture2. In capture3 i tested another format 432x246 4:2:0 8 bit it works great. 
### capture1
![capture1](https://cloud.githubusercontent.com/assets/9120336/13842327/d52ee02e-ec2d-11e5-9384-4e79945e7195.PNG)
### capture2
![capture2](https://cloud.githubusercontent.com/assets/9120336/13842326/d52e2be8-ec2d-11e5-8109-00a34cf83867.PNG)
### capture3
![capture3](https://cloud.githubusercontent.com/assets/9120336/13842444/770b882a-ec2e-11e5-9afc-aca37c11c7c2.PNG)

**Comment by ChristianFeldmann** [comment]
Hi gnobbi,
that definitely looks strange. It would be great if you could provide the yuv file that does not work to us. Then I could take a look into the matter. If possible, please E-mail the file to:
feldmann@ient.rwth-aachen.de
Best regards,
Christian

**Comment by gnobbi** [comment]
I provided to you.

**Comment by ChristianFeldmann** [comment]
The bug is fixed in all active branches. An always up to date windows build of the master branch (including this patch) can be downloaded from: http://www.ient.rwth-aachen.de/~blaeser/YUViewWinRelease/YUView-1-0-LATEST-MinGW-x64.exe

**Comment by gnobbi** [comment]
thanks a lot
