### ISSUE TITLE
Detect ``UV(A) Interleaved`` option in yuv filename for NV12 format

### ISSUE THREAD

**Issue by PharrellWANG** [IENT/YUView#221]
Just like resolution 2160x1440 can be detected from filename ``Something_2160x1440_60_8_somethingMore.yuv``, how to indicate current yuv file is ``UV(A) Interleaved`` in filename?

**Comment by ChristianFeldmann** [comment]
Hi.
You are right that format can not really be detected through the filename. Do you have a good suggestion how this could look then I can add it. Maybe:
```
Something_2160x1440_60_8_yuvinterlaced.yuv
Something_2160x1440_60_8_interlaced.yuv
Something_2160x1440_60_8.yuvinterlaced
Something_2160x1440_60_8_yuv420pInterlaced.yuv
Something_2160x1440_60_8_yuv420pUVI.yuv
```

I actually like the last two options best to give an explicit description of the yuv format.

**Comment by PharrellWANG** [comment]
> Hi.
> You are right that format can not really be detected through the filename. Do you have a good suggestion how this could look then I can add it. Maybe:
> 
> ```
> Something_2160x1440_60_8_yuvinterlaced.yuv
> Something_2160x1440_60_8_interlaced.yuv
> Something_2160x1440_60_8.yuvinterlaced
> Something_2160x1440_60_8_yuv420pInterlaced.yuv
> Something_2160x1440_60_8_yuv420pUVI.yuv
> ```
> 
> I actually like the last two options best to give an explicit description of the yuv format.

**Comment by PharrellWANG** [comment]
@ChristianFeldmann I think the last one looks good, ``Something_2160x1440_60_8_yuv420pUVI.yuv``

**Comment by ChristianFeldmann** [comment]
I added a function to detect the formats correctly. So using `yuv420pUVI` should give you the right YUV format. Also why doing this I noticed that there already is a way to detect the NV21 format: You can just name you file "something.nv21". That should work :)
