### ISSUE TITLE
Cannot drag file to playlist

### ISSUE THREAD

**Issue by adahbingee** [IENT/YUView#226]
Drag file to playlist is avaliable before the newest v2.6
please fix

**Comment by ChristianFeldmann** [comment]
Hi.
Could you please provide some more information here? What platform are you on? How did you download YUView? I am on windows and there it works as intended.

**Comment by adahbingee** [comment]
I'm using windows 10
Automatic upgrade.

**Comment by ChristianFeldmann** [comment]
Ok me too. I am also using the installed version and I can drag/drop items from the explorer into the playlist. Please note that dropping only works on the playlist itself (where the items are shown) and not onto the central split view widget. 
I am not excluding that there is an issue with the automatic update somehow. Could you try to reinstall YUView? Maybe that fixes it. But there is no issue that I am aware of.

**Comment by adahbingee** [comment]
I reinstall and no problem occur.
Thank you very much.
