### ISSUE TITLE
How can I find "libVTMDecoder.dll"?

### ISSUE THREAD

**Issue by Sumjack** [IENT/YUView#227]
- OS: window10
- IDE: VisualStudio 2019
- YUView 2.6
- VTM 7.3

I want to see a bitstream video encoded by VTM, but I couldn't find libVDMecoder.dll
How can I find it?

![image](https://user-images.githubusercontent.com/38426593/79356166-93765e80-7f79-11ea-8206-6fd6db814bfa.png)

**Comment by ChristianFeldmann** [comment]
Hi. I am sorry but I did not finish the libVTM repo to build prebuild libraries yet. I created a repository here (https://github.com/ChristianFeldmann/VTM). Unfortunately the VTM version is not up to date so the decoder interface will have to be ported. Please feel free to do this :)
I will try to get to this soon.

**Comment by ChristianFeldmann** [comment]
Ok actually I don't know why I closed this. This is a feature request for this and I will reopen until the libvtm decoder is done.

**Comment by ChristianFeldmann** [comment]
Work to-do:

- [x] Add parsing of VVC annex B
- [x] Add bitrate plotting (AU detection)
- [x] Add the decoding library interface to vvdec
- [x] Integrate vvdec with the new interface into YUView

**Comment by ChristianFeldmann** [comment]
This was actually done and merged. So vvdec is now supported for VVC decoding. Also VVC bitstream parsing works now. Have fun testing it!

**Comment by faymek** [comment]
OS: Manjaro
IDE: VS Code
YUView 2.7
VTM 11.0

Hello, can you explain how to set the VVC decoder on Linux? Just make the source, from VTM I get `DecoderAppstatic` and from VVdeC I get `vvdecapp`. Found nothing like `libVTMDecoder`. And also please update the wiki. Many Thanks!

**Comment by zimba77** [comment]
> I want to see a bitstream video encoded by VTM, but I couldn't find libVDMecoder.dll How can I find it?
> 
The latest decoder dll is here:
https://vcgit.hhi.fraunhofer.de/delagrangep/VVCSoftware_VTM/-/commit/09c9d397f8cff4e207ce2c6b42f8e3a7a2c5a67e

direct link to download:
https://vcgit.hhi.fraunhofer.de/delagrangep/VVCSoftware_VTM/-/blob/09c9d397f8cff4e207ce2c6b42f8e3a7a2c5a67e/lib/libvtmdec.dll

MartinEesmaa has plugins for Linux VLC here:
https://github.com/MartinEesmaa/VVCEasy/blob/e5dcb6a531ae8ea809de1f658234828491c1214f/INSTALLVLCPLUGIN/libvvcdecoder_plugin.so
https://github.com/MartinEesmaa/VVCEasy/blob/e5dcb6a531ae8ea809de1f658234828491c1214f/INSTALLVLCPLUGIN/libvtmdec.so
