### ISSUE TITLE
Difference Sequence presenting not existing diff

### ISSUE THREAD

**Issue by farzadshbfn** [IENT/YUView#240]
Comparing the same RGBA32 and BGRA32 raw_video formats, will show diff on the UI.

This happens when all R G B A values match and in diff layer, values of all R G B A are 0. But UI shows a massive diff between the two files.

Probably because R & B components are swizzled in the internal file, logic detects a diff, but in presentation there's no difference.

**Comment by farzadshbfn** [comment]
UI samples of the result are uploaded [here](https://ibb.co/8B0FSwX) & [here](https://ibb.co/0hWwtVn)

**Comment by ChristianFeldmann** [comment]
Hi thanks for the report. I tried to recreate this but I was not able to. I took the png image that you provided and converted it to an `rgba` file using ffmpeg but I am not able to see any difference. All pixels are shown in grey (no difference) as expected. Could you maybe provide a sample raw RGB file to me so I can try to recreate it using that?

**Comment by farzadshbfn** [comment]
Hi, sorry I missed your follow-up.
Of-course, I uploaded two files [here](https://gofile.io/d/9vth2v).
One of them is 176x144_BGRA32 and the other one is 176x144_RGBA32. If you create a diff sequence you'll see that the diff sequence will present a blue-ish surface on the screen.

P.S: This is the command I use to convert them together via ffmpeg:
```sh
./ffmpeg -f rawvideo -pix_fmt rgb32 -video_size 176x144 -i 176x144_RGBA32.rgb \
-f rawvideo -pix_fmt bgr32 -s 176x144 176x144_BGRA32.rgb
```

**Comment by ChristianFeldmann** [comment]
@farzadshbfn Sorry but the link does not seem to work. I am getting `The upload does not exist`

**Comment by farzadshbfn** [comment]
Oh boy, I was trying to use one of public websites and it's just not working 🤦🏻‍♂️
I uploaded them to my GoogleDrive, hope [this one works](https://drive.google.com/drive/folders/15ub2y7MTqI1tHYiVKE6CAVogX8uwSdyL?usp=sharing)

**Comment by ChristianFeldmann** [comment]
Yes that worked. Thank you!

**Comment by ChristianFeldmann** [comment]
Fixed. This only happened in case of different formats for the RGB files. For the difference I would use the wrong pixel format and get the wrong data from the arrays.
