### ISSUE TITLE
Incorrect YUV Values when zoomed in

### ISSUE THREAD

**Issue by rcswift** [IENT/YUView#241]
When inspecting YUV values of an image the U and V values are always displayed as the same value (Cr value is correct, the Cb value instead shows the Cr value) even though the pixels are colored correctly. The attached sample image 'test.yuv' (YUV Planar 4:2:2 10-bit BE) and screenshot demonstrate the problem. 

![test_yuv_screenshot](https://user-images.githubusercontent.com/9707141/85804515-d68e4400-b717-11ea-996e-e9ac50e16d19.png)

[test.yuv.txt](https://github.com/IENT/YUView/files/4834271/test.yuv.txt)
(Remove the .txt extension to view the file)

**Comment by ChristianFeldmann** [comment]
Thanks for the bug report. Especially the test file helps a ton. I will take a look at this.

**Comment by ChristianFeldmann** [comment]
The zoom box also reports the correct values.

**Comment by ChristianFeldmann** [comment]
Now that was a stupid typo. Fixed.
