### ISSUE TITLE
xmmintrin.h no such file or directory on ARM Nvidia Jetson TX2

### ISSUE THREAD

**Issue by RobertSte** [IENT/YUView#245]
Hi,

I tried to compile on my Nvidia Jetson TX2 developer kit with Ubuntu 18.04 LTS.

I get the error in the title, seems like this software needs x86 specific libs. Any chance for ARM here?

Best regards!

**Comment by ChristianFeldmann** [comment]
Sorry that was by accident. The header is only needed if you explicitly enable the SSE implementation (whic is off by default). I also put the header into the `#if` block so now it should compile. I never got around completing the SSE implementation really. ARM optimizations would also be interesting but that is not something that is really planned.

**Comment by RobertSte** [comment]
I checked your commit out but get another error:

`src/filesource/fileSource.cpp: In member function ‘virtual QList<infoItem> fileSource::getFileInfoList() const’:
src/filesource/fileSource.cpp:129:34: error: ‘const class QFileInfo’ has no member named ‘birthTime’
   QString createdtime = fileInfo.birthTime().toString("yyyy-MM-dd hh:mm:ss");
                                  ^~~~~~~~~
Makefile:1916: recipe for target 'fileSource.o' failed
`
Thanks for the fast response!

**Comment by ChristianFeldmann** [comment]
The function `birthTime` was introduced with Qt 5.10. So possibly you just need a newer Qt version.
