### ISSUE TITLE
YUView MacOS Performance Improvement

### ISSUE THREAD

**Issue by aachenmax** [IENT/YUView#253]
I believe I finally discovered one of the potential reasons for bad performance of YUView on MacOS:

Problem: Open a long AVC Bitstream (20min+) and hit play --> Playback speed is maybe 5fps on a native MacBook. A profiler / stack trace reveals that the app is spending an awful amount of time doing this in qmacstyle_mac.mm:

```  
                    if (hasTicks && drawTicks) {
                        if (!drawBar && hasDoubleTicks)
                            slider.numberOfTickMarks = numberOfTickMarks;

                        [cell drawTickMarks];
                        ...
 
```
It constantly redraws an awful amount of ticks on our QSlider playback controller. Maybe this is a bug or just the underlying NSSlider implementation is very bad.

Solution: Turn off the ticks on the QSlider --> Enjoy excellent performance!

A permanent workaround could be to turn off tick marks if there are more than a fixed number of frames in the file. @ChristianFeldmann What do you think about this?

**Comment by ChristianFeldmann** [comment]
What the *?&". 😆 
I would have never suspected that. I will have to re-check the code but I think I was just relying on the Qt implementation to draw less ticks marks (which seems to be working on other platforms). But nice then we might only have to add a smart tick function or something. 
Did you try this with the 2.7 release too? Because I updated Qt there too.

**Comment by ChristianFeldmann** [comment]
Related to: https://github.com/IENT/YUView/issues/80

**Comment by aachenmax** [comment]
I tested it with Qt 5.14 but not on the latest commit in the master branch.

**Comment by ChristianFeldmann** [comment]
In the 2.7 release I upgraded Qt to 5.14.2.

**Comment by aachenmax** [comment]
Oh and the MacOS version I am running is Catalina 10.15.5

**Comment by ChristianFeldmann** [comment]
Searched the Qt bugtracker but could not find a reported bug related to this.

**Comment by aachenmax** [comment]
Yes, the problem still exists in the 2.7 release. I am opening the bitstream, get maybe 2 fps and the fan turns on after 10s

**Comment by fjaeger** [comment]
Slightly off-topic: @aachenmax , you are using a Mac now? :D

**Comment by aachenmax** [comment]
@fjaeger Sometimes you have to go with the flow :) But don't worry, there is always a Windows 10 VM booted up, just in case :D

**Comment by ChristianFeldmann** [comment]
A colleague has an old Mac book he can borrow to me. Then I can see to reproduce this.
And Fabaian. What are you doing here :D

**Comment by fjaeger** [comment]
What I am doing here? Just for your information, I am one of the owners of the _IENT_ team here at GitHub! 👨‍💼

I keep getting notifications about every single activity within this team, so I know precisely what you are doing 🧐

**Comment by ChristianFeldmann** [comment]
Uh the big Boss. Sorry Boss. Will find the bug Boss 😛

**Comment by ChristianFeldmann** [comment]
Ok I created a small test with a QSlider and a timer to just update it. And this is definitely a weired bug in Qt. On windows + ubuntu you can easily set the ticks to 10000 and redraw the slider 100 times per second. On Mac the redraw rate drops to like 3 fps for only 1000 ticks. Even with only 100 ticks the fps drops to 30. I think for now the solution is to disable ticks on Mac and I will create a bugreport in Qt.

**Comment by ChristianFeldmann** [comment]
Qt Bugreport: https://bugreports.qt.io/browse/QTBUG-85663
