### ISSUE TITLE
Wiki: contributing development vs. develop?

### ISSUE THREAD

**Issue by uartie** [IENT/YUView#264]
https://github.com/IENT/YUView/wiki/How-to-contribute says to submit contributions to the `development` branch.  But it appears this branch may have been renamed to `develop`.  Is `develop` the correct branch now?  If so, please update wiki.

**Comment by ChristianFeldmann** [comment]
Thanks for the hint. Yes I changed this to reflect the more common naming. I updated the wiki accordingly.
