### ISSUE TITLE
Ubuntu 20.04 install beginner question

### ISSUE THREAD

**Issue by jeffreylee523** [IENT/YUView#266]
Hi, newbie here.  running ubuntu 20.  trying to install YUView from snap and got ffmpeg fails. tried building from repo, qmake and make.  seems good, but don't know how to start the program.  running sudo make install in hopes to create a desktop icon to open, and getting this error, "No rule to make target '/YUViewLib/libYUViewLib.a', needed by 'YUView'.  Stop."  Appreciate any help.  Thank you

**Comment by ChristianFeldmann** [comment]
Hi! 
I just tested this in a Ubuntu 20 docker container and there everything works. I just checked out the code, built it and installed it.

```
git clone https://github.com/IENT/YUView.git
cd YUView
mkdir build
cd build
qmake ..
sudo make install
```

Afterwards the YUView app was located in /usr/local/bin. How did you compile YUView?

**Comment by ChristianFeldmann** [comment]
If this does not work please let me know. I will close this for now.
