### ISSUE TITLE
error opening file using libavcodec

### ISSUE THREAD

**Issue by Aaron-Cai** [IENT/YUView#267]
Failed to opening an MP4 file on macOS Catalina, showing error message: "error opening file using libavcodec"

**Comment by ChristianFeldmann** [comment]
Hi. Sorry to hear that. But I will need some more information then that to help. What version of ffmpeg do you have? What version of YUView do you have? Are you compiling YUView on your own? Did you just download it from the releases page?

**Comment by Aaron-Cai** [comment]
It's just the latest version downloaded from the releases page(https://github.com/IENT/YUView/releases/tag/2.7).
Shoud I install the ffmepg lib by myself?

**Comment by ChristianFeldmann** [comment]
Yes YUView does not ship with ffmpeg. It can only use ffmpeg which you must install through some other means. There is more information in the [Wiki](https://github.com/IENT/YUView/wiki/FFmpeg).

**Comment by Aaron-Cai** [comment]
Thanks. Problem solved.

**Comment by ValZapod** [comment]
There is also a problem that it is still using av_register_all() which was removed.
