### ISSUE TITLE
Build with error:  optional: No such file or directory

### ISSUE THREAD

**Issue by kinhum** [IENT/YUView#272]
g++ -c -pipe -O2 -fPIC -std=gnu++1z -Wall -W -D_REENTRANT -DYUVIEW_HASH="\"0\"" -DYUVIEW_VERSION=\"0\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o parserAnnexB.o src/parser/parserAnnexB.cpp
In file included from src/parser/common/BitratePlotModel.h:40:0,
                 from src/parser/parserAnnexB.h:40,
                 from src/parser/parserAnnexB.cpp:33:
src/ui/views/plotModel.h:41:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.

**Comment by ChristianFeldmann** [comment]
Hi. 
The error indicates that you are compiling without C++17 support (which introduces optional).
Some more info would be very helpful: 
 - What platform are you on? What g++ are you using?
 - What version of YUView are you trying to compile?

**Comment by kinhum** [comment]
Hi Christian,
Thanks for your support.
system info:
5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
gcc version:
gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026

**Comment by kinhum** [comment]
Hi Christian,

I am trying to compile YUView-develop.zip. And I will step back to YUView-2.7.zip.
Thanks

kinhum

**Comment by ChristianFeldmann** [comment]
Yes you can revert back to an older version which does not yet use `optional` but that does not sound like a good solution. 
The problem seems to be your GCC version. 6.5.0 is pretty old and Ubuntu 18.04 through apt should ship with 7.6. Your could try to update your system (`sudo apt update`) which should update your GCC.

**Comment by kinhum** [comment]
Hi Chirstian,
I upgraded gcc and it is resolved.
Thanks.

Kinhum
