### ISSUE TITLE
Show video with correct SAR

### ISSUE THREAD

**Issue by HarHarLinks** [IENT/YUView#283]
I am working with material from a PAL DVD (i.e. 720x576 interlaced) that I first ripped (remuxed) and then deinterlaced and encoded as AVC using ffmpeg (x264): `ffmpeg -i MyDVDRip.mkv -vf yadif -c:v h264 -crf 18 -preset veryslow MyDVDRip-yadif.mp4`.

Notably, PAL uses non-square pixels (16:15), correctly displayed in the Bitstream Analysis -> Stream Info tab under Sample aspect ratio.

```
ffprobe MyDVDRip.mkv
[...]
Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 1k tbn, 50 tbc

ffprobe MyDVDRip-yadif.mp4
[...]
Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x576 [SAR 16:15 DAR 4:3], 5522 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
```

I happened to compare the clip to another (third) 720x576 video that uses SAR 1:1 (square pixels). Surprisingly, both are rendered at the same size in YUView.

Comparing the two clips with another tool, e.g. [Identity](https://gitlab.gnome.org/YaLTeR/identity), they are displayed with their correct (D)AR.

**Comment by ChristianFeldmann** [comment]
Hi. Thanks for the report. I also noticed this already but did not open an Issue yet. You are right. Currently only square pixel formats are supported. Any signaling of non-square formats will just be irgnored.
While this is definitely possible it will also require quite some work to fix this as many of the functions that draw things (e.g. grid, pixel values, rulers, ...),  currently rely on the pixels to be square.

**Comment by ChristianFeldmann** [comment]
Hi. I just merged a scale filter which should enable what you are looking for. Just add an item to the playlist, right click on it and add a resampler. There you can scale the image to your liking. If the bitstream contains SAR info you can also use that to auto calculate the display resolution.
Let me know if there are any issues with this new feature.
