### ISSUE TITLE
[win10]crash when parse container by ffmepg.

### ISSUE THREAD

**Issue by perfectsun1990** [IENT/YUView#285]
lib version:https://github.com/BtbN/FFmpeg-Builds/releases
yuview is latest version.YUView 2.7

you can use any file ,such as a mov mkv etc.

**Comment by ChristianFeldmann** [comment]
I think this is related to a bug which I fixed already but we need a new release.

**Comment by ChristianFeldmann** [comment]
Hi I just released another version of YUView with some fixes that I did recently. One of the fixes was related to ffmpeg parsing. Could you try again with the latest 2.8 release? Thanks,

**Comment by ChristianFeldmann** [comment]
I will close the issue now. Please reopen if the test did not succeed.
