### ISSUE TITLE
UI disaply tips:

### ISSUE THREAD

**Issue by perfectsun1990** [IENT/YUView#286]
![image](https://user-images.githubusercontent.com/22425871/96973437-77680100-154a-11eb-8c01-2a50253d2cc2.png)
I find yuview parse 264/265 only show the keyword , count we display more informations?
cur:
![image](https://user-images.githubusercontent.com/22425871/96977155-476f2c80-154f-11eb-951a-68cbc09ff99a.png)

**Comment by ChristianFeldmann** [comment]
Hi.
I am not sure what you mean. Why do you see this as a useless view? What could be better?
Have you tried clicking the small arrow on the left (or double click the entry) which will expand the NAL view and reveal the parsing of the flags.

**Comment by perfectsun1990** [comment]
Hi! This is just one of my suggestions. I would like to see a view associated with hexadecimal and corresponding 264/265 fields. What I expect display style just like another software interface I showed in the issue. many thanks to your job!-------- 原始邮件 --------发件人： Christian <notifications@github.com>日期： 2020年10月23日周五 17:31收件人： IENT/YUView <YUView@noreply.github.com>抄送： sunpf <perfectsun1990@163.com>, Author <author@noreply.github.com>主    题： Re: [IENT/YUView] UI disaply tips: (#286)
Hi.
I am not sure what you mean. Why do you see this as a useless view? What could be better?
Have you tried clicking the small arrow on the left which will expand the NAL view and reveal the parsing of the flags.

**Comment by ChristianFeldmann** [comment]
Did you press the arrow to the left and open up the hierarchy which shows you all of the details that you are looking for? Here is a screenshot of the view when you open up the SPS NAL unit for example: 
![image](https://user-images.githubusercontent.com/11556397/97078025-37a42680-15e9-11eb-8028-1f4d0e5c68ef.png)
It shows you the symbols and the bits that were read from the bitstream. What advantage would a hex view have? You can open a hex editor if you want to see the hex values.

**Comment by perfectsun1990** [comment]
> Did you press the arrow to the left and open up the hierarchy which shows you all of the details that you are looking for? Here is a screenshot of the view when you open up the SPS NAL unit for example:
> ![image](https://user-images.githubusercontent.com/11556397/97078025-37a42680-15e9-11eb-8028-1f4d0e5c68ef.png)
> It shows you the symbols and the bits that were read from the bitstream. What advantage would a hex view have? You can open a hex editor if you want to see the hex values.

yes, I had tried it!  But I think  it's better to show  a complete NALU's hex and it's mapped field at the same time.
pre software Link: https://github.com/zymill/flvAnalyser
Best wishes!

**Comment by ChristianFeldmann** [comment]
Ok got it. Sorry but I see absolutely no advantage in that. So I will not implement this. But please go ahead if you like the idea. This is an open source project afterall. 🙂
