### ISSUE TITLE
error opening file using libavcodec on Ubuntu16.04

### ISSUE THREAD

**Issue by DerekChen88** [IENT/YUView#288]
Hello, I just meet the problem that I have installed ffmpeg. But when I open a video(such as mp4), in the left hand side "info" tab it shows all ffmpeg informations, but it still told me error opening file using libavcodec.
I tried v2.3, 2.4 and 2.8 and always the same problem.
Also I run "sudo apt-get install ffmpeg" several times to make sure ffmpeg is the newest version.(ffmpeg is already the newest version (7:2.8.17-0ubuntu0.1).)

![Screenshot from 2020-11-04 19-53-45](https://user-images.githubusercontent.com/55443712/98108752-77b3b500-1ed7-11eb-8172-e56591bfec1f.png)

And when I try to specify the loction of those four ffmpeg libraries in the setting , it return me an error log:

loadFFMpegLibrarySpecific Trying to load libraries avFormat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 avCodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 avUtil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 swResample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1
loadFFMpegLibrarySpecific Try to load libAvutil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 success
loadFFMpegLibrarySpecific Try to load libSwresample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 success
loadFFMpegLibrarySpecific Try to load libAvcodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 success
loadFFMpegLibrarySpecific Try to load libAvformat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 success
resolveAvCodec Error loading the avcodec library: Can't find function avcodec_parameters_alloc.
bindFunctionsFromLibraries Binding functions failed
loadFFMpegLibrarySpecific Trying to load libraries avFormat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 avCodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 avUtil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 swResample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1
loadFFMpegLibrarySpecific Try to load libAvutil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 success
loadFFMpegLibrarySpecific Try to load libSwresample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 success
loadFFMpegLibrarySpecific Try to load libAvcodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 success
loadFFMpegLibrarySpecific Try to load libAvformat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 success
resolveAvCodec Error loading the avcodec library: Can't find function avcodec_parameters_alloc.
bindFunctionsFromLibraries Binding functions failed
loadFFMpegLibrarySpecific Trying to load libraries avFormat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 avCodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 avUtil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 swResample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1
loadFFMpegLibrarySpecific Try to load libAvutil /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 success
loadFFMpegLibrarySpecific Try to load libSwresample /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 success
loadFFMpegLibrarySpecific Try to load libAvcodec /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 success
loadFFMpegLibrarySpecific Try to load libAvformat /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 success
resolveAvCodec Error loading the avcodec library: Can't find function avcodec_parameters_alloc.
bindFunctionsFromLibraries Binding functions failed

**Comment by ChristianFeldmann** [comment]
Hi. Sorry to hear that it is not working for you. What the error messages says it that YUView was not able to find the function avcodec_parameters_alloc in the libraries. I am suspecting that that the ffmpeg version you have is too old. I would suggest to try with a newer version of ffmpeg (there may be one available precompiled for Ubuntu 16. Or you can compile it from source). 
We have deprecated support for Ubuntu 16. 18 is the minimum version we support and test.

**Comment by ChristianFeldmann** [comment]
I will close this for now because (I am sorry but) we will not support Ubuntu 16.04 specifically anymore.
