### ISSUE TITLE
Improve ability to compare videos of different resolutions

### ISSUE THREAD

**Issue by dpasqualin** [IENT/YUView#294]
Hi, I'm experimenting increasing the video resolution while keeping the target bitrate and would like to visually compare the results, but I can't find a way to downscale/upscale the videos in the YUView.

This is how they look in the UI, but it would be easier to compare if I could have one of them upscaled or downscaled to match the other.
![example](https://user-images.githubusercontent.com/68142/100365390-b41e9080-2fff-11eb-9997-0144445a194d.png)

Thank you for your time.

**Comment by ChristianFeldmann** [comment]
Hi. Yes that would be cool. I don't run into this situation too often but it would be nice. Implementation wise it could be combined with #283 maybe. 
Idea: Have a nested `scaling` Item in the playlist (like the difference item) that rescales a video that you put into it to a different resolution. Then it could do both. Rescale to any resolution / SAR.

**Comment by ChristianFeldmann** [comment]
Hi. I just merged a scale filter which should enable what you are looking for. Just add an item to the playlist, right click on it and add a resampler. There you can scale the image to your liking and then use it in the split view to show it side by side.
Let me know if there are any issues with this new feature.
