### ISSUE TITLE
v2.8, win10, .msi, error opening file using libavcodec

### ISSUE THREAD

**Issue by jeffreylee523** [IENT/YUView#297]
Hi, just installed again.  I've always gotten this message.  what am i missing?  I used the windows .msi installer downloaded today.  thanks in advance.

**Comment by ChristianFeldmann** [comment]
You need to install / download ffmpeg with shared libraries for yuview to work. See https://github.com/IENT/YUView/wiki/FFmpeg

**Comment by jeffreylee523** [comment]
Thank you.  I'm not a programmer, so i'm a bit lost.  Apologies.  I downloaded a package, but it has .exe in it, not the dlls.  If i run the exe, i get a flash of a script running but no indicator i did anything.  sorry for the ignorance.  i've seen friends use this tool and its awesome.

**Comment by jeffreylee523** [comment]
there has to be an easier way to get the 4 .dlls.  i've got them individually from dll-files.com, but the swresample won't load.  tried -2 and -3 versions.  sorry again for the newb pestering.

**Comment by jeffreylee523** [comment]
loadFFMpegLibrarySpecific Trying to load libraries avFormat C:/Program Files/YUView/avcodec/avformat-55.dll avCodec C:/Program Files/YUView/avcodec/avcodec.dll avUtil C:/Program Files/YUView/avcodec/avutil-56.dll swResample C:/Program Files/YUView/avcodec/swresample-2.dll
loadFFMpegLibrarySpecific Try to load libAvutil C:/Program Files/YUView/avcodec/avutil-56.dll success
loadFFMpegLibrarySpecific Try to load libSwresample C:/Program Files/YUView/avcodec/swresample-2.dll fail: Cannot load library C:\Program Files\YUView\avcodec\swresample-2.dll: The specified module could not be found.
loadFFMpegLibrarySpecific Unloading already loaded libraries
loadFFMpegLibrarySpecific Trying to load libraries avFormat C:/Program Files/YUView/avcodec/avformat-55.dll avCodec C:/Program Files/YUView/avcodec/avcodec.dll avUtil C:/Program Files/YUView/avcodec/avutil-56.dll swResample C:/Program Files/YUView/avcodec/swresample-2.dll
loadFFMpegLibrarySpecific Try to load libAvutil C:/Program Files/YUView/avcodec/avutil-56.dll success
loadFFMpegLibrarySpecific Try to load libSwresample C:/Program Files/YUView/avcodec/swresample-2.dll fail: Cannot load library C:\Program Files\YUView\avcodec\swresample-2.dll: The specified module could not be found.
loadFFMpegLibrarySpecific Unloading already loaded libraries
loadFFMpegLibrarySpecific Trying to load libraries avFormat C:/Program Files/YUView/avcodec/avformat-55.dll avCodec C:/Program Files/YUView/avcodec/avcodec.dll avUtil C:/Program Files/YUView/avcodec/avutil-56.dll swResample C:/Program Files/YUView/avcodec/swresample-2.dll
loadFFMpegLibrarySpecific Try to load libAvutil C:/Program Files/YUView/avcodec/avutil-56.dll success
loadFFMpegLibrarySpecific Try to load libSwresample C:/Program Files/YUView/avcodec/swresample-2.dll fail: Cannot load library C:\Program Files\YUView\avcodec\swresample-2.dll: The specified module could not be found.
loadFFMpegLibrarySpecific Unloading already loaded libraries

**Comment by ChristianFeldmann** [comment]
I think I can see your problem. The Zanoe build that I am referencing seem to be not available anymore. I update the page in the wiki. Please give that explanation another go: https://github.com/IENT/YUView/wiki/FFmpeg
I just tested those two new build and they both work for me.

**Comment by jeffreylee523** [comment]
that worked to get me going.  i can open mp4 now thank you.  except, i have raw .avi that when i open it crashes.  is there a crash log i can look for?  thanks again for your help and for putting this thing together.

**Comment by jeffreylee523** [comment]
that worked to get me going.  i can open mp4 now thank you.  except, i have raw .avi that when i open it crashes.  is there a crash log i can look for?  thanks again for your help and for putting this thing together.

**Comment by ChristianFeldmann** [comment]
Can you play the avi file using ffplay? Unfortunately there is no log in case YUView crashes. But there are definitely some things in there which may create a crash like this. If you are able to share the file with me I could debug the issue.

**Comment by jeffreylee523** [comment]
sorry for the size 330MB.  i was afraid if i saved it from another tool, it would change something.

https://drive.google.com/file/d/1R2tnQbj9wnTvn5FLD2tucCi6sNs1w3H5/view?usp=sharing

Thank you

**Comment by ChristianFeldmann** [comment]
Its fixed. There was a bug with compressed files which contain raw rgba (with alpha plane) data. Fixed in develop.
