### ISSUE TITLE
Two different window modes: Single Window and Multiple Windows

### ISSUE THREAD

**Issue by fjaeger** [IENT/YUView#3]
We should have two different window configurations:
- Single window with decibel utility widgets and the playback widget in the middle
- Multiple windows (one for the playlist/statistics, one for utility widgets and one for the playback related widgets)

**Comment by aachenmax** [comment]
Questions for all:
1. Do we want the three separate windows (playback,playlist,inspector) to be docked into a "control" window for the separate window mode?
2. Do we need the menu bar (File, View etc.) in the video window?

**Comment by fjaeger** [comment]
My opinion:

1. Sounds interesting. Maybe we don't even need a special window, because undocked panels are also individual windows, right?!
2. as it is still the primary window, I would say yes.
