### ISSUE TITLE
How can I download "libVTMDecoder.dll"?

### ISSUE THREAD

**Issue by bouaafia23** [IENT/YUView#302]
Hello,  

Could you tell me how to download "libVTMDecoder.dll" as it is not found in YUView files?

Thank you in advance.

**Comment by ChristianFeldmann** [comment]
Hi. I updated the wiki page to include the links: https://github.com/IENT/YUView/wiki/External-Decoders
You can also navigate from YUView to the download pages in Help -> Downloads.

**Comment by bouaafia23** [comment]
I can't find the ''LIBVTMdecoder.dll'' file via this link.

**Comment by ChristianFeldmann** [comment]
Ah I am sorry it looks like I never finished the libVTM integration and build. I will still leave this issue closed because there already is one: https://github.com/IENT/YUView/issues/227
