### ISSUE TITLE
YUV400p16le and gray16le in names

### ISSUE THREAD

**Issue by dbonattoj** [IENT/YUView#310]
Thanks for the nice software!

I usually work with YUV 4:0:0 16-bit LE files,
it would be very nice to add "YUV400p16le" tag or at least the same as ffmpeg "gray16le" to infer the type from the filename.

(or I'm totally missing something and a tag already exists?)

I think it should be somewhere around this:
https://github.com/IENT/YUView/blob/8a6ff0ad9167da3392ffd196b1b8a8d0ad5e1b3b/YUViewLib/src/video/yuvPixelFormatGuess.cpp#L225

Thanks!

**Comment by ChristianFeldmann** [comment]
Hi I just looked at the code and I think you are right that none of the existing guessing functions will work for this. But you are also right that "YUV400p16le" is very descriptive and should actually work. I will add this. 
Is `gray16le` the pixel format you can use in ffmpeg to do this conversion?

**Comment by dbonattoj** [comment]
Thanks!

Yes, I'm using gray16le to view my YUV in png format.

`ffmpeg -s 1920x1080 -pixel_format gray16le -i z_1920x1080_YUV400p16le.yuv -frames:v 1 z_1920x1080_YUV400p16le.png`

Here is a link to a sample file if you need:
https://owncloud.ulb.ac.be/index.php/s/YERXSR4K0FpFiXm

With the corresponding output
![z0008y0323x0438_1920x1080_YUV400p16le](https://user-images.githubusercontent.com/28501597/104164736-a890f880-53f8-11eb-89d9-0c76a1b1cc72.png)

**Comment by nolyn** [comment]
with #349 having "YUV400p16le" as part of the file name should work

**Comment by ChristianFeldmann** [comment]
There was actually a different issue here which was that lower and uppercase was checked wrong. Now the case is ignored. I also added a guess for the specific "grayXle" string.
