### ISSUE TITLE
I422_LE

### ISSUE THREAD

**Issue by lgammo** [IENT/YUView#326]
Is this format on your todo list?

**Comment by ChristianFeldmann** [comment]
Hi!
Sorry what do you mean exactly? 422 le is definitely already supported. If not, could you please give a link to a specification or an example file which does not work?
Thanks.

**Comment by lgammo** [comment]
Perhaps I didn't notice it on the YUV Format drop down list?

**Comment by lgammo** [comment]
Specifically, 10 Bit format, not 8 bit.

**Comment by lgammo** [comment]
I see, it is under 'custom' formats.
