### ISSUE TITLE
UYVP format display

### ISSUE THREAD

**Issue by lgammo** [IENT/YUView#330]
How can I display this format:
**"UYVP"** packed 10-bit 4:2:2 YUV (U0-Y0-V0-Y1 U2-Y2-V2-Y3 U4 ...)

Thanks!

**Comment by lgammo** [comment]
Never mind. I had U and V reversed.

**Comment by ChristianFeldmann** [comment]
So you made it work? Nice 🙂

**Comment by lgammo** [comment]
No I did not. I thought I had. I was trying with a file generated by gstreamer (1.16):
./gst-launch-1.0 videotestsrc pattern=4 ! video/x-raw,format=UYVY,width=1280,height=720 ! filesink location=UYVY_red.yuv

**Comment by ChristianFeldmann** [comment]
Ok. If you could provide a small test file I could test if this is supported.

**Comment by lgammo** [comment]
gzipped file containing what should be UYVP 10 bit packed format generated by gstreamer.

[UYVP_red.yuv.gz](https://github.com/IENT/YUView/files/6286528/UYVP_red.yuv.gz)

**Comment by ChristianFeldmann** [comment]
Ok I fixed it. There was no implementation for the specific byte packing for 10 bit 422. Now it works. I think. I am now seeing a completely red picture. 
Please give it a try. The latest develop verison should contain the fix. And reopen if it does not work.

**Comment by lgammo** [comment]
Settings that work: 422, 10 bit, LE, packed, UYVY, byte packing @1280x720.

Thank you.
