### ISSUE TITLE
Compilation fails with Qt 6

### ISSUE THREAD

**Issue by picard314** [IENT/YUView#331]
Hi, amazing developer~

As the title, I encountered such problems during 'Build'. Have you met before..? Thanks for your attention!

**Comment by ChristianFeldmann** [comment]
Hmm this sounds like the compiler can not find the required Qt include files. But the description is a bit short to draw any other conclusions. So I would need much more info to give further tips like: What operating system do you use? Have you installed Qt? How? What version? Also a snippet from the compiler output with an actual error message would help.

**Comment by picard314** [comment]
It is so good to hear from you! I am at Mac-10.15.7 with qt-6.0.2 and Qt Creator-4.14.1 (not sure why qt6 is accompanied with QC4) installed. 

I received 

1. 'QRegExp' file not found  [at FileSource.cpp, line 37]
2. 'QLabel' file not found     [at saveUi.h, line 35]
3. 'QDialog' file not found    [at statisticsstylecontrol.h, line 35]

You are right probably include files are missing. I pray they may hide somewhere else but e.g. changing 
#include < QDialog>  
with
#include <QtWidgets/QDialog> 
contributes almost nothing but generates new errors.

I've git clone your newest codes and built them.

Thanks for reading..!

**Comment by ChristianFeldmann** [comment]
Aah then that may be the reason. So far I did not do any tests with Qt 6 yet. Also in CI we are only testing the versions that come with the package management systems (So only 5.xx versions). 
Ususally they try to not break stuff but the major version bump may cause some problems ... I will have to investigate this. 
Just out of curiosity: How did you install Qt 6 on the mac? With the official download from the QT site or using some package management system?

**Comment by picard314** [comment]
Thanks for your valuable information! Then I've uninstalled qt6 and installed qt5.15.2. Now your project can be built at Qt Creator-4.14.1! Very amazing effects your YUView provides!

(Un)Installations at my side rely on homebrew.

Just an inquiry please，，could your YUView play multiple streams simultaneously？As sometimes I need to compare '' 'before' and 'after' algorithm-process '' of a stream in a comfortable way.

**Comment by ChristianFeldmann** [comment]
Awesome. I will still leave this open as we need to make this compile. We want to update sooner or later. 
Yes you can look at two items side by side. Right click on the central view and enable `Split View` --> `Side-by-side`. Then select two items in the playlist (Ctr click).

**Comment by picard314** [comment]
Thanks a lot and look forward to your exciting news! 

Yeah she works! Thanks again!

**Comment by ChristianFeldmann** [comment]
I made YUView compile with Qt6. There was actually not that much to fix. The only thing I want to do before merging this is:

- [ ] Add a test for the csv parser. I changed something here. We need a test for this part.
- [ ] Lets also update our dependencies to Qt6

**Comment by picard314** [comment]
WOW! Geek u r! Thanks for your exciting information!! :)

**Comment by ChristianFeldmann** [comment]
Ok so our dependencies are not yet update but with this PR it should from now on compile with Qt6 as well.

**Comment by picard314** [comment]
Thanks for letting me know. :) It is surely tough work as I've been told recently that Qt6 is "short of several components/modules" compared to earlier Qt versions..

**Comment by ChristianFeldmann** [comment]
Yes they removed some deprecated modules. For YUView only the QRgx (legacy regexp parser) was affected and I replaced it. And some minor API changes in other modules.

**Comment by picard314** [comment]
:) Not an easy operation for me or other fresh qt6 users may I say, to tackle such a bunch of branches of change.
