### ISSUE TITLE
Can't open V210

### ISSUE THREAD

**Issue by icegull** [IENT/YUView#333]
I found that YUView 2.1.0 can't open 10bit-UYVY-422 file(V210), I tried to use "UYVY4:2:2 10-bit LE packed" and "UYVY4:2:2 16-bit LE packed", both can't work. YUVIEW display nothing. Could you check please?

**Comment by ChristianFeldmann** [comment]
Hi! 
Its always possible that there is one YUV format that is not yet supported. Could you provide an example file and maybe a link to some specification how it looks like?

**Comment by icegull** [comment]
> Hi!
> Its always possible that there is one YUV format that is not yet supported. Could you provide an example file and maybe a link to some specification how it looks like?

**Comment by icegull** [comment]
> Hi!
> Its always possible that there is one YUV format that is not yet supported. Could you provide an example file and maybe a link to some specification how it looks like?

[https://www.dropbox.com/s/yxjadl1iqbv9etz/v210.yuv?dl=0](url)
Hello sir. Here is the V210 file. It's 10bit UYVY 4:2:2le packed format.
And there is a spec doc may help:
[https://developer.apple.com/library/archive/technotes/tn2162/_index.html#//apple_ref/doc/uid/DTS40013070-CH1-TNTAG8-V210__4_2_2_COMPRESSION_TYPE](url)

Thank you very much for you reply.

**Comment by ChristianFeldmann** [comment]
Ok I got the file and looked at the description. Yes that is a format that I did not see before and that we do not have support for. Will see how we can add this.

**Comment by icegull** [comment]
> Ok I got the file and looked at the description. Yes that is a format that I did not see before and that we do not have support for. Will see how we can add this.

Thank you sir. Then the YUView will be more perfect. ;-)

**Comment by ChristianFeldmann** [comment]
I think the way forward is to add the option for specific YUV formats which don't fit the pattern that we have established. This will be a bit of work though. 
@icegull Could you tell me the resolution of the sequence you shared?

**Comment by icegull** [comment]
> I think the way forward is to add the option for specific YUV formats which don't fit the pattern that we have established. This will be a bit of work though.
> @icegull Could you tell me the resolution of the sequence you shared?

OK. It's 1920x1080. Happy to see that we have a plan for it.  
You can try this tool or ffplay to view the v210:
1. [https://github.com/daiybh/yuvplayer](url)
2. ffplay from ffmpeg

**Comment by nolyn** [comment]
following  [https://lists.ffmpeg.org/pipermail/ffmpeg-user/2015-May/026690.html](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2015-May/026690.html) I was able to display the file.

`
ffmpeg -r 25 -s 1920x1080 -pix_fmt yuv422p10le -vcodec v210 -i tmp/v210.yuv -vcodec  ffvhuff  tmp/out.avi
`

then YUView can display the resulting avi. A way to allow display of uncommon formats would be to have an interface where one can input the correct ffmpeg options. Assuming ffmpeg supports all the formats required.

**Comment by ChristianFeldmann** [comment]
I merged support for the V210 pixel format. With the structures I put in place we are also setup to support all sorts of crazy packings which are out there. 
So @icegull please give it a try. The latest develop should work. 
Just a funny side not: I looked at the code of it in ffmpeg and the "codec" `v210` that they have in there is basically just a conversion from this packed format to yuv42210p and thats it. It is not actually a video codec.

**Comment by icegull** [comment]
> I merged support for the V210 pixel format. With the structures I put in place we are also setup to support all sorts of crazy packings which are out there.
> So @icegull please give it a try. The latest develop should work.
> Just a funny side not: I looked at the code of it in ffmpeg and the "codec" `v210` that they have in there is basically just a conversion from this packed format to yuv42210p and thats it. It is not actually a video codec.

Wonderful. Could you make a new package for me? So I can help to validate it.

**Comment by ChristianFeldmann** [comment]
You can always compile YUVIew yourself or you can get the latest outputs from the github actions CI from the page of the build like this one: https://github.com/IENT/YUView/actions/runs/739196629

**Comment by icegull** [comment]
> You can always compile YUVIew yourself or you can get the latest outputs from the github actions CI from the page of the build like this one: https://github.com/IENT/YUView/actions/runs/739196629

It works perfectly. Congratulations!

**Comment by ChristianFeldmann** [comment]
Awesome then we can close this. Enjoy :)
