### ISSUE TITLE
Playback stops when changing sequence

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#35]
the playback is paused when a different sequence is selected (development branch)

**Comment by ChristianFeldmann** [comment]
This is not a bug but a design decision. Should this be changed? I think it makes sense that the playback is stopped when a new sequence is selected. If you have a different suggestion then what should happen instead? At what frame should playback continue in the new sequence? The current fram or the start?

**Comment by nolyn** [comment]
I agree that for many sequences it won't make sense. But it could be useful
for multi view sequences.
Am 12.05.2016 1:34 nachm. schrieb "Christian" <notifications@github.com>:

**Comment by ChristianFeldmann** [comment]
This is now switchable in the settings.
