### ISSUE TITLE
some problems about compiling the source code

### ISSUE THREAD

**Issue by tju-zxy** [IENT/YUView#352]
Thanks for your great work! However, when I compiled the YUView from source codes in Qt creator, I met the problem as follows.

:-1: error: No rule to make target 'E:/YUView-2.10/build-YUView-Desktop_Qt_5_12_0_MinGW_64_bit-Debug/YUViewLib/YUViewLib.lib', needed by 'YUView.exe'.  Stop.

Could you tell me how to address this problem?  My development environment is win10, Qt 5.12.0, MinGW

**Comment by ChristianFeldmann** [comment]
Hi!
Hmm that is a good question. We are not actively supporting MinGW on windws but only the visual studio compiler so I have not tested this for a long long time. How exactly did you try the build? Which version of MinGW? I am guessing you just downloaded the Qt minGW version from the Qt page? Did you use the latest develop branch?
Christian

**Comment by tju-zxy** [comment]
@ChristianFeldmann Thanks for your reply! I just built the YUViewer via clicking the 'build' button in the Qtcreator. The version of MinGW is 7.3.0. I have utilized the source code in the latest branch. so can I just follow the process to compile the code in ./github/workflows?

**Comment by ChristianFeldmann** [comment]
Yep the github workflows is a good way to recreate how we build YUView using the Visual Studio compiler. You just need the compiler (which can be freely downloaded from microsoft; you don't need to buy visual studio for this) and the msvc version of Qt.

**Comment by tju-zxy** [comment]
Thanks for your help! I still have a problem. Currently, I want to add a new image-coding format different from YUV or RGB. The image array is composed of spike data. Which part of the source code should I rewrite?

**Comment by ChristianFeldmann** [comment]
Ah so were you able to compile it now? That is good to hear. 
Ok I am not quite sure what format that is. What you need is basically the functionality to convert whatever your input is to an 8 bit RGB image of a certain size which is drawn by YUView. E.g. for YUV the `videoHandlerYUV` does this conversion from YUV to RGB. So depending on your format you could implement a `videoHandlerSpikeData` or similar which does this conversion. And then it depends a bit how the data looks and where it comes from if you would implement a custom `playlistItemSomethingFile` or if you could use the already existing `playlistItemRawFile`.

**Comment by tju-zxy** [comment]
I am able to compile it using the Visual Studio compiler now, thanks for your help!  I will try what you said to rewrite some functions and implement my work.
