### ISSUE TITLE
Can support Truevision TGA format?

### ISSUE THREAD

**Issue by icegull** [IENT/YUView#358]
Hi guys. It's me again. Last time I requested V210 support, you made it. it's a amazing.
So can I ask if can support Truevision TGA format?

I can give some info:
[https://en.wikipedia.org/wiki/Truevision_TGA](url)
[http://www.paulbourke.net/dataformats/tga/](url)

And I upload one TGA pic into dropbox if you need:
https://www.dropbox.com/s/g5qd44dau0mk6yd/nba.1920x1080.tga?dl=0
You can view it by acdsee or something like TGA viewer.

Thank you very much. It will make our video encoder engineer life more eaier.

**Comment by ChristianFeldmann** [comment]
Hmm ... I thought Qt natively supports loading of `.tga` images but seems I was wrong. At least I was not able to open the tga file that you provided just by using QImage. So there is no super trivial solution to this unfortunately. 
The only possible way I found is to parse targa images ourselves. The format is 30+ years old so there are no licensing problems and the format also does not seem to be too complex. A good starting point I found is a reference reading implementation here: https://github.com/aseprite/tga

So definitely interesing but I don't have any practical use from it so it is really low on my priority list. If you want to give a go please go ahead. The way I would approach is it:
- Check out the code in the reference implementation
- Create a new function that gets the filename and loads the image into a QImage. Then plugging that into the playlistItemImageFile is easy. 
- Adapt the code from the reference implementation to directly work on QImages

**Comment by icegull** [comment]
> Hmm ... I thought Qt natively supports loading of `.tga` images but seems I was wrong. At least I was not able to open the tga file that you provided just by using QImage. So there is no super trivial solution to this unfortunately.
> The only possible way I found is to parse targa images ourselves. The format is 30+ years old so there are no licensing problems and the format also does not seem to be too complex. A good starting point I found is a reference reading implementation here: https://github.com/aseprite/tga
> 
> So definitely interesing but I don't have any practical use from it so it is really low on my priority list. If you want to give a go please go ahead. The way I would approach is it:
> 
> * Check out the code in the reference implementation
> * Create a new function that gets the filename and loads the image into a QImage. Then plugging that into the playlistItemImageFile is easy.
> * Adapt the code from the reference implementation to directly work on QImages

Thanks for your reply. Indeed there are two kinds of TGA. Compressed and uncompressed. The uncompressed TGA is much easier, since it's just a 16 bytes header with RGBA pic follow. So I think display RGBA is not hard.

**Comment by ChristianFeldmann** [comment]
Ok I don't know what happened there but I added support for TGA. Enjoy.

**Comment by icegull** [comment]
Awesome. It works perfectly. Thanks for your support!
