### ISSUE TITLE
what a pity that this software can not display the value of y,u,v pixel..

### ISSUE THREAD

**Issue by xiaoxiongli** [IENT/YUView#362]
what a pity that this software can not display the value of y,u,v pixel..

**Comment by nolyn** [comment]
It can. You need to zoom in or enable the "Zoom Box" from the context menu.

**Comment by ChristianFeldmann** [comment]
If you zoom in enough it looks like this: 

![image](https://user-images.githubusercontent.com/11556397/116676927-e0bc4700-a9a7-11eb-9548-03adcc8d43d2.png)

And if you turn on the "Zoom Box" it reports Y/U/V values like this:

![image](https://user-images.githubusercontent.com/11556397/116676979-f29dea00-a9a7-11eb-9224-4004a7c39d48.png)

Please re-open if this is not what you are looking for.
