### ISSUE TITLE
H.265 bitstream analysis crash in latest version 2.11

### ISSUE THREAD

**Issue by chhuanb** [IENT/YUView#379]
YUView crashed when the bitstream analysis was toggled.
![image](https://user-images.githubusercontent.com/6419381/122498069-0f0de880-d021-11eb-8f67-c5f590739dba.png)

**Comment by ChristianFeldmann** [comment]
That was quick after the release 😆 
Looks like we have not enough tests in place. So you just open an HEVC stream and then it crashes? Or does it crash when you activate the statistics? (Because you posted a screenshot of this).

**Comment by ChristianFeldmann** [comment]
Yep I can recreate this by opening an HEVC stream and then activating any statistics (like Pred mode). Will fix it. Thanks for the report.

**Comment by ChristianFeldmann** [comment]
The fix is building. Since the release has been so close I will just hotfix it with the fixed version in a few minutes.

**Comment by ChristianFeldmann** [comment]
Hotfix release is released.
