### ISSUE TITLE
custom gradient doesn't apply upon selecting custom

### ISSUE THREAD

**Issue by HarHarLinks** [IENT/YUView#388]
When I select custom gradient, even though the range colors appear set, they are not actually applied (actual state is like the preview shows). Nor does updating the range change anything.
![image](https://user-images.githubusercontent.com/2803622/125290002-24c0b600-e320-11eb-8db2-59919012d439.png)

Hitting OK here and re-editing the same now shows the range's actual colors, which are white and white in this case.
It would be nice if instead of "the preview", the range was applied. That usually fits my use case and intention.

Version: git from AUR, which is v2.11.1-4-g168a55cb

**Comment by ChristianFeldmann** [comment]
Should be fixed in develop. Please reopen if you still see this behavior.
