### ISSUE TITLE
Crash on mouseover of packets in bitrate plot

### ISSUE THREAD

**Issue by jonno85uk** [IENT/YUView#390]
Noticed that whilst mouseovering the bitrate plot it kept crashing.
Whilst attached to a debugger I noticed an uninitialised variabled.

![mouseover](https://user-images.githubusercontent.com/14606456/125532092-292045d0-f2c4-4c87-9f36-cd8680556137.PNG)
[mouse_over_bitrate_plot_crash.patch.txt](https://github.com/IENT/YUView/files/6812244/mouse_over_bitrate_plot_crash.patch.txt)

Checked-out version: 168a55cb980f78bad907a28e2b7a0a2da84b1622

**Comment by ChristianFeldmann** [comment]
Hi.
That is super strange as a QString should always be initialized. And by default it should just be empty. So this is highly unusual. I added some code that might also be the cause of this which checks when looking into the bitrate entry list. Could you try the latest develop build if it still happens?

**Comment by jonno85uk** [comment]
Yes, it is strange. I thought the same too. I checked on another PC with same Qt + mingw and it didn't crash there.

Anyways, latest version fixed this crash.
