### ISSUE TITLE
automatic reloading of images does not work

### ISSUE THREAD

**Issue by HarHarLinks** [IENT/YUView#392]
Whenever I load an image (bmp, png, jpg, ...) and it gets updated, yuview notifies me and asks to reload it. However the Item View keeps showing the old contents, even when switching back and forth between playlist items. To work around this, I need to close the image and open it anew.

Version: git from AUR, v2.11.1-4-g168a55cb

**Comment by ChristianFeldmann** [comment]
I was able to recreate it.

**Comment by ChristianFeldmann** [comment]
Fixed.
