### ISSUE TITLE
[crash] floating point exception (core dumped) with SAR scaling

### ISSUE THREAD

**Issue by HarHarLinks** [IENT/YUView#401]
follow-up to #283

hitting this button with certain videos crashes the app
![image](https://user-images.githubusercontent.com/2803622/128046911-726fdde7-3f6e-486c-bd9d-ba17cf7058b1.png)

is there a way for me to generate debug logs?

Edit:
I suppose this is the problem...
![image](https://user-images.githubusercontent.com/2803622/128047155-a4df8b0d-b084-4d98-810d-30a29f18615c.png)

Why is the SAR given twice anyway?

**Comment by ChristianFeldmann** [comment]
Hi! Thanks for the report. Fixed in develop.
There are two values reported because they are gotten from different parts of FFmpeg. One comes from the container and the other from the codecInfo.
