### ISSUE TITLE
Can't save custom colormaps

### ISSUE THREAD

**Issue by rapierx** [IENT/YUView#403]
Every time I open a new video I need to configure custom colormaps. How can I force a custom colormap to be used in every video?

![edit colormap yuview](https://user-images.githubusercontent.com/8772696/128266259-00ded5f7-7f6e-4671-9bdf-cc66ed502764.png)

I always redo this customization when opening new videos.

**Comment by ChristianFeldmann** [comment]
There is currently no functionality that can do this. How do you think this could look like? Maybe we could save some custom maps in the settings and then show them in the drop-down.

**Comment by rapierx** [comment]
> Maybe we could save some custom maps in the settings and then show them in the drop-down.

Yeah, that should be good.

**Comment by ChristianFeldmann** [comment]
So it just took too long but I finally made it work. So you can now have custom colormaps and save them (throught QSettings) and just select them from a dropdown list.
