### ISSUE TITLE
No packets shown in packet analysis with very small mov/mp4 files

### ISSUE THREAD

**Issue by jonno85uk** [IENT/YUView#405]
Hi.

I have been learning how mp4+avc are demuxed/parsed and have stumbled across something which i'm not sure is a bug in YUView or ffmpeg (the program I used to create  the files, version 4.2.4).

With certain mp4/mov files, no packets are shown in packet analysis for any stream despite being playable in video players (mpv/vlc).

If I look at each video packet I notice none of them have a sync-code 0x000001. As for the audio packets, I can't guess as to why they are not being parsed in YUView.

I've included 2 samples of where i've noticed this issue (seems to limited to these small clips i am working with)

https://user-images.githubusercontent.com/14606456/128612572-447ad323-4458-45da-9f3d-578c56e8d8cb.mov

![Screenshot from 2021-08-07 23-48-00](https://user-images.githubusercontent.com/14606456/128615678-c32f4853-5d1c-4f65-b75c-c809d00cd408.png)

YUView version: 2dfea38d24352e061dcf1b5fab9a5a9079c765db

**Comment by jonno85uk** [comment]
So i've done a little digging in ffmpeg seeing as it can parse the packets. It has 2 methods of parsing them:

1. if the format is avc the 1st 4bytes are the size of the nal
2. otherwise look for the sync-code

To find if avc or not, byte 1 of the AVC decoder configuration atom (stbl/stsd/avc1/avcC) is checked. I think this is found in AVCodecContext->priv_data (H264Context*)

**Comment by ChristianFeldmann** [comment]
Thanks for the report. I am able to reproduce it with the file you provided.

**Comment by ChristianFeldmann** [comment]
Fix will be merged once the CI passes

**Comment by jonno85uk** [comment]
@ChristianFeldmann thanks. That fixed it
