### ISSUE TITLE
How can i get Command Line version of `yuvview`?

### ISSUE THREAD

**Issue by qxlsz** [IENT/YUView#422]
How can i get Command Line version of `yuvview`?

**Comment by ChristianFeldmann** [comment]
Hi! For what exactly? What should that do?

**Comment by ChristianFeldmann** [comment]
I will close this for now. If you still think this is a good idea please reopen and let me know what this should do exactly.

**Comment by qxlsz** [comment]
i meany, i want to convert a yuv image to jpg/png from the command line. sorry for the delayed response.
