### ISSUE TITLE
Could not load .h266 file of my own file

### ISSUE THREAD

**Issue by MartinEesmaa** [IENT/YUView#424]
Hello! I encoded from YUV to .h266 file using VVENC.

When I try load my own .h266 file, it gives me message:
![couldnotload123](https://user-images.githubusercontent.com/88035011/137838443-6510728d-8e4e-4823-bbda-797a309ef719.png)

Error: Decoding of the frame not possible:
The frame could not be decoded. Possibly, the bitstream is corrupt or was cut at an invalid position.
So I just want a view .h266 file, but I decoded .h266 to .yuv, it works.

Example of loaded .h266 file, that I wanna look this:
![simpleh266file](https://user-images.githubusercontent.com/88035011/137838737-63555419-d549-46a6-a7a0-376f04e8db44.png)

Any solutions to load my own .h266 file? Note: I loaded correctly dll of vvdec
- MartinHero

**Comment by ChristianFeldmann** [comment]
Hi! 
This might be a parsing error in YUView because some bitstream feature is not supported yet. Without access to the file it will be impossible to fix though. Could you provide access to the file?

**Comment by MartinEesmaa** [comment]
Okay @ChristianFeldmann, I will give you file here.

Input 8 bit view YUV (854x480): 
[RAWINPUT8BITYUV.zip](https://github.com/IENT/YUView/files/7379120/RAWINPUT8BITYUV.zip)

Output .h266 file (not loaded with Version v2.11.1, 854x480): 
[extremeh266.zip](https://github.com/IENT/YUView/files/7379111/extremeh266.zip)

Example .h266 that file loaded (6 minutes playing of 1080p):
https://ln5.sync.com/dl/0ef33da60/dkbnhtvy-9aabe9er-fvxn7dnv-vy9jycnx

Please let me know for notice.

Regards
- MartinHero13

**Comment by ChristianFeldmann** [comment]
Hi! 
So I just tested the file that you marked as non working with the latest develop branch and it works for me. So it looks like this was already fixed in develop. Can you please test and confirm this?
Christian

**Comment by MartinEesmaa** [comment]
Your develop branch work with my loaded own .h266 file, but I tried compile with Qt and it was very hard to make this, because I installed anaconda and I'm very confused, that there is no develop version (.exe), so where can I get develop branch version, not the releases stable example June 2021. Can you send to me of your YUView develop branch (.exe Windows and others Mac and Linux)?

**Comment by ChristianFeldmann** [comment]
I am not sure what you mean with Anaconda. Do you mean the package manager which is used on some distros? If so, then there is probably some way to install Qt using it. And then building should be easy. 
However, each build here in the Github CI also saves the outputs as artifacts. E.g. here (https://github.com/IENT/YUView/actions/runs/1365560321) are the artifacts for the latest develop build.

**Comment by MartinEesmaa** [comment]
Ok thank you @ChristianFeldmann, it worked with develop version.
![itworked123](https://user-images.githubusercontent.com/88035011/138611004-7051a244-c3fd-48d4-9b8f-7e00beb7df7f.png)

I will close this issue.
- MartinHero
