### ISSUE TITLE
RGBA1555/BRGA5551 support

### ISSUE THREAD

**Issue by dawnminghuang** [IENT/YUView#441]
HI:
    any consider to support RGB componet only 5bit, a 1bit raw data.
    thank you.

**Comment by ChristianFeldmann** [comment]
Hi! 
No no plans for that so far. But that is just because I did not know they existed. Do you have any documentation on the format? 
Implementing new formats is also quite easy. If you could use some tips let me know.

**Comment by ChristianFeldmann** [comment]
Ok I did a quick search and found this as a reference: https://cboard.cprogramming.com/c-programming/118698-color-conversion.html
Looks very easiy to add. @dawnminghuang could you provide a sample file in this format? That would be super helpful for the implementation.

**Comment by dawnminghuang** [comment]
[RGB.zip](https://github.com/IENT/YUView/files/7821702/RGB.zip)
sorry for late reply. I upload two sample file.
