### ISSUE TITLE
CLI tool to convert yuv images to png

### ISSUE THREAD

**Issue by qxlsz** [IENT/YUView#448]
**Is your feature request related to a problem? Please describe.**
I always have to load the yuv images manually and then set the resolution. If there is a way to convert the images by feeding the inputs through args. that would be better

**Describe the solution you'd like**
A command line interface binary to trigger so I can pass the path to yuv view images and the resolution details along with the format

**Describe alternatives you've considered**
writing my own yuv converter.

**Comment by ChristianFeldmann** [comment]
Hi! I have a question: Is your goal just to open the files in YUView and then view them or to save them as png? Because if you want a CLI that can read a YUV file and save it as PNG then ffmpeg can do that for you.

**Comment by ChristianFeldmann** [comment]
I will close this for now since I don't understand the problem and solution yet and there was no further response. Please reopen in case you can further describe how / what YUView should do. 
Btw: If you indicate the resolution of the YUV file in the filename, YUView will use that.
