### ISSUE TITLE
YUView and FFmpeg 5.0

### ISSUE THREAD

**Issue by ChristianFeldmann** [IENT/YUView#449]
**Describe the bug**
FFmpeg 5.0 does not seem to be supported yet. I heard that some API changes were performed which yuview does not support yet.

**Error**
```
resolveAvFormat Error loading the avformat library: Can't find function av_register_all.
```

**Version (please complete the following information):**
 - OS: All
 - Version: latest develop

**Comment by ValZapod** [comment]
> I heard

From me. :)

**Comment by ChristianFeldmann** [comment]
This should be working now. Please give it a try! 🙂

**Comment by ValZapod** [comment]
It works :)
