### ISSUE TITLE
resolveAvFormat Error loading the avformat library: Can't find function av_register_all

### ISSUE THREAD

**Issue by HOWARD201314** [IENT/YUView#457]
mac, when add ffmpeg libraries. have following issue:

"loadFFMpegLibrarySpecific Trying to load libraries avFormat /usr/local/Cellar/ffmpeg/5.0/lib/libavformat.59.16.100.dylib avCodec /usr/local/Cellar/ffmpeg/5.0/lib/libavcodec.59.18.100.dylib avUtil /usr/local/Cellar/ffmpeg/5.0/lib/libavutil.57.17.100.dylib swResample /usr/local/Cellar/ffmpeg/5.0/lib/libswresample.4.3.100.dylib
loadFFMpegLibrarySpecific Try to load libAvutil /usr/local/Cellar/ffmpeg/5.0/lib/libavutil.57.17.100.dylib success
loadFFMpegLibrarySpecific Try to load libSwresample /usr/local/Cellar/ffmpeg/5.0/lib/libswresample.4.3.100.dylib success
loadFFMpegLibrarySpecific Try to load libAvcodec /usr/local/Cellar/ffmpeg/5.0/lib/libavcodec.59.18.100.dylib success
loadFFMpegLibrarySpecific Try to load libAvformat /usr/local/Cellar/ffmpeg/5.0/lib/libavformat.59.16.100.dylib success
resolveAvFormat Error loading the avformat library: Can't find function av_register_all.
bindFunctionsFromLibraries Binding functions failed"

**Comment by ChristianFeldmann** [comment]
Same as: https://github.com/IENT/YUView/issues/449. This is because of FFmpeg 5.0. Was already fixed. Please try the latest version on develop.
