### ISSUE TITLE
Failed to load ffmpeg library

### ISSUE THREAD

**Issue by whyuu** [IENT/YUView#460]
**Describe the bug**
Failed to load ffmpeg library

**To Reproduce**
1.   Open h264 encoded file

**Expected behavior**
The file can be loaded successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/8078262/164422459-76c98814-303f-4dab-9b2f-b91d17d84ede.png)
![image](https://user-images.githubusercontent.com/8078262/164423867-40903807-0a57-4c5e-933f-02fd284d08a7.png)

**Version (please complete the following information):**
 - OS: windows
 - Version v2.12.1-81-g824f4fbb
 - QT 5.14.2

**Comment by ChristianFeldmann** [comment]
Thank you for the report. This somehow slipped in with the ffmpeg code refactor I did. Fixed.
