### ISSUE TITLE
Make regular grid color configurable

### ISSUE THREAD

**Issue by ChristianFeldmann** [IENT/YUView#473]
**Is your feature request related to a problem? Please describe.**
In some situations, the color of the drawn grid is not visible (e.g. dark sequence).

**Describe the solution you'd like**
It would be nice to be able to select the color of the grid.

**Describe alternatives you've considered**
No

**Comment by adamws** [comment]
Hi, I think this feature already exist: `File->Settings->General->View Grid Line Color`
![image](https://user-images.githubusercontent.com/12676586/202847733-42b76c66-7e2b-4073-92bd-ce8d29d1ab8f.png)

Or perhaps it's something different you are looking for.

**Comment by ChristianFeldmann** [comment]
:D Awesome I forgot that I already added this. But I think the positioning of the setting could be a bit better. It would be cool to also be able to select this through the context menu.

**Comment by adamws** [comment]
Here is my proposition https://github.com/IENT/YUView/commit/6e72a09a12dfe3c54895225e6926cfe743f38abd

[grid-color.webm](https://user-images.githubusercontent.com/12676586/203052016-d3d4fddb-ad1b-46f5-ab2d-9600ea1f16dd.webm)

Still need to figure out how to synchronize with Settings dialog window.

**Comment by ChristianFeldmann** [comment]
Its actually a tiny bit easier then your code. Please see the PR. Once it compiles I will merge it.

**Comment by ChristianFeldmann** [comment]
Alright I merged this.
