### ISSUE TITLE
Crash: pressing delete on a file opened using ffmpeg

### ISSUE THREAD

**Issue by ValZapod** [IENT/YUView#483]
**Describe the bug**

**To Reproduce**

Open any tiff, e.g. https://github.com/MediaArea/MediaInfoLib/files/5526175/tiff-with-icc.zip
Select compressed file to open using ffmpeg
Press delete on a newly added file in a playlist 
Crash.

**Expected behavior**
No crash.

**Screenshots**

**Version (please complete the following information):**
 - OS: [e.g. iOS] windows 11
 - Version [e.g. 2.2.1, commit gb283bgrj] HEAD of master
 - If you compiled YUView yourself then which Qt version did you use?

**Comment by ChristianFeldmann** [comment]
Hi thanks for the report. I am trying to reproduce this. Unfortunately I was not really successful with this. Although I have observed it also for me (also on windows) once in a while. Maybe it also depends a bit also on the ffmpeg version. Which version are you using? I tried 4.4.1 and 5.0 but no success so far.

**Comment by ValZapod** [comment]
I use official master https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by ChristianFeldmann** [comment]
Thanks for the hint. I tried the most recent version from there but still no luck 🙁

**Comment by ValZapod** [comment]
Still happens on latest commit from 3 days ago. Do you want a stack trace (but I would need to compile it myself)?

![image](https://user-images.githubusercontent.com/31514790/218045308-2611c6f4-f743-401e-8a81-a9e60fd68500.png)

**Comment by ValZapod** [comment]
OMG. After update to libavcodec     60 and all deprecation removal ity broke audacity but no longer crashes. Closing, was bug in ffmpeg. HAHAHAHA. https://github.com/FFmpeg/FFmpeg/commit/5bad4856035ca5ed571e9d7d9b1d503a5c9ef0a5

**Comment by ChristianFeldmann** [comment]
Aah cool to hear that it ultimately worked out for you. Yes dynamic library dependencies can be a pain. But still thanks for opening the issue here so that other people with the same problem can also find it.

**Comment by ValZapod** [comment]
@elenril Wanted to mention that whatever you did Anton, it fixed this issue, which is strange, but nice. Dynamic loading related crash inside windows kernel. Considering ffmpeg is supposed to be a library, crash on exit was a deal breaker.

**Comment by ValZapod** [comment]
May be related to https://trac.ffmpeg.org/ticket/10210#comment:6

fixed in major 60.
M
