### ISSUE TITLE
Error opening file: unable to obtain frame size from file

### ISSUE THREAD

**Issue by xyz1001** [IENT/YUView#505]
**Describe the bug**
YUView fail to open a h264 file generated by ffmpeg. ffplay is ok.

**To Reproduce**
1. Generate a h264 file by command `ffmpeg -f lavfi -i testsrc=duration=10:size=1281x721:rate=30 test.h264`
2. Open the file with YUView.

**Expected behavior**
YUView can open the file normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/14332136/216528640-c42b640a-b49f-466b-8553-f338260d5b5a.png)

**Version (please complete the following information):**
 - OS: Windows 11 22H2
 - Version 2.13

** attachment
- [The h264 file generated by ffmpeg](https://github.com/IENT/YUView/files/10576168/test.zip)

**Comment by ChristianFeldmann** [comment]
I was able to reproduce this behavior on the latest develop version. Thx for the file and the report ...

**Comment by ChristianFeldmann** [comment]
Alright this is fixed. The issue was that the h264 bitstream was in 4:4:4 subsampling and there were two tiny bugs hiding in the code. We are overdue again for a release so I will do one.
