### ISSUE TITLE
Make release naming more consistent

### ISSUE THREAD

**Issue by frankplow** [IENT/YUView#526]
**Describe the bug**
Some of the releases have a full stop after the `v`, e.g. `v.2.13`, whereas some do not, e.g. `v2.12.1`

**To Reproduce**
N/A

**Expected behavior**
I realise this appears nitpicky, however consistent release naming makes it easier to support the software in package managers. It would be amazing if the releases could be renamed to have a consistent style.

**Screenshots**
N/A

**Version (please complete the following information):**
N/A

**Comment by ChristianFeldmann** [comment]
Hi! Yep the `.1` version you mentioned was because I just added a tiny bugfix. Or I did something tiny wrong in the release. I can't even remember. What would you recommend? Maybe do you have a link to a common scheme that is used most commonly? For me it does not matter. Its just a counter up.

**Comment by frankplow** [comment]
Hi, I think the easiest is just to remove the dots on `v.2.12` and `v.2.13` as the majority seem to omit them. Mixing three or two levels to the version hierarchy is fine, it's more just the formatting. Thanks for your quick response!

**Comment by ChristianFeldmann** [comment]
Ah yes that is quite inconsistent. There should not be a dot and it should be `v2.13`. I agree. I think I can just rename them. There should not be an issue. May I ask what automated tool you are trying out there?

**Comment by ChristianFeldmann** [comment]
I was able to add new corrected tags to the released versions.

**Comment by frankplow** [comment]
@ChristianFeldmann I'm using Homebrew. In particular, the reason I noticed this is that Homebrew has a feature called livecheck which searches the releases page to detect new releases and flag when the package is out-of-date. It does this by extracting the version number with a regex, which is usually just the version number itself and no leading `v` or whatever. The different naming then means that the package maintainer potentially has to manually update the URL each time, they can't just do, for example, `https://github.com/IENT/YUView/releases/download/v#{version}/YUView-Mac.zip`

Thanks for getting this fixed so quickly!

**Comment by ChristianFeldmann** [comment]
But for the regex you can also have it work with and without a dot: `(.)?`. But I will not try to make the same mistake again :)

**Comment by frankplow** [comment]
The regex does extract the version number correctly, i.e. it gets `2.13` for `v.2.13` and `2.13` for `v2.13`, it's putting this version number back into the URL for the download link that causes the issue. It would be fine if the version number had a leading `.`, but I don't think Homebrew likes this as it compares version numbers.
