### ISSUE TITLE
release it's binary without qt, it can be use in some automaic test and provide help doc for all orginal UI's parameters

### ISSUE THREAD

**Issue by guilvge** [IENT/YUView#528]
**Is your feature request related to a problem? Please describe.**
now I want to develop a automaic tools to verify many yuv format yuv file and turn them into BMP file to check the last 
BMP file to see weather the yuv format is right, but it seems it only have to start up with QT ui. it can't be use to develop
automaic tools.

**Describe the solution you'd like**
I hope if it is possible to provide just binary with many arguements to replace with QT's parameters interface.
**Describe alternatives you've considered**

**Comment by ChristianFeldmann** [comment]
Hi! So you mean a command line only tool for conversions? I think this is not the project for you. I would recommend the swiss army knife: `ffmpeg`. That is completely CLI and can convert YUV to BMP.
