### ISSUE TITLE
RawFile info parsing by filename need bugfix

### ISSUE THREAD

**Issue by for13to1** [IENT/YUView#547]
**Describe the bug**
In the older version (like 2.13), when *.yuv file or *.rgb file be added to playlist, the width/height/pixel_format/bit_depth can be guessed from the filename and be filled into the info chart automatically. Image can can be showed smoothly as you open it.

Now in the newest version, it failed to display  this type of raw data automatically, until you set the size/format/bitdpth info on the right pane specifically.
It prompts like "With the given settings, the YUV data can not be converted to RGB:"
But the yuv file size is OK and surely can be converted to RGB.

**To Reproduce**
1. Go to 'PlayList'
2. Click on 'Open'
3. Add a normal yuv file with filename containing the size/format/bitdepth info

**Expected behavior**
The yuv file can be showed normally and smoothly

**Screenshots**
![image](https://github.com/IENT/YUView/assets/115892874/e8ba7aa2-b1d6-4edf-8123-e5c4815264f7)

The corresponding yuv file is uploaded here:
[512x512_444p_8bit-chessboard_16m16_(0_128_128)_(255_128_128).zip](https://github.com/IENT/YUView/files/13463329/512x512_444p_8bit-chessboard_16m16_.0_128_128._.255_128_128.zip)

**Version (please complete the following information):**
 - OS: Windows 11
 - Version: 2.14

**Comment by ChristianFeldmann** [comment]
Hi! Thank you for the report. This was a quick one to fix. I am working a bit to refactor the internal code to have a clear separation from Qt as much as possible. In that I forgot this signed unsigned edge case. 
I am, however, a bit confused about the rest of the changes you made in the linked PR. Did you also have an issue with other extensions / formats? That might be another issue.

**Comment by ChristianFeldmann** [comment]
Fix is merged. Please comment here or open a new issue if not all you issues were addressed.
