### ISSUE TITLE
When using full range option open full range yuv, pixel 255 is displayed as 235

### ISSUE THREAD

**Issue by 21pages** [IENT/YUView#550]
**To Reproduce**
`original.png`
![original](https://github.com/IENT/YUView/assets/14891774/a3c20a72-76b5-4638-908c-3c28ca0d251a)

1. `ffmpeg -i "original.png"  -pix_fmt yuv420p -sws_flags spline+accurate_rnd+full_chroma_int -color_range 2 -colorspace 5 -color_primaries 5 -color_trc 6 "fullrange_601_420.yuv"`
2. Open `fullrange_601_420.yuv` with `ITU-R.BT601`, normal
3. Change color convertion to  `ITU-R.BT601 Full Range`, pixel 255 shows as 235

**Expected behavior**
Show normally when open full range yuv with full range option.
If it is my misunderstanding, could you give it an explaination?

**Screenshots**
![image](https://github.com/IENT/YUView/assets/14891774/2f8e9aa8-ac0f-4a0c-beac-ea6dd638c45b)
![image](https://github.com/IENT/YUView/assets/14891774/3f6055d5-affe-46de-80cb-aed21dcf43ce)

**Version (please complete the following information):**
 - OS: win11
 - Version 2.14

**Comment by ChristianFeldmann** [comment]
Hi! Thank you for the report. 
I am having problems to recreate the issue on my end. I was unable to download / view the png that you linked here. I don't seem to have access. Could you somehow send that to me?
I just created a white (RGB 255,255,255) png and converted it to YUV using the ffmpeg command that you provided there. But I do get a YUV with limited range (the luma values are 235 as they should be for limited range). Maybe that is the issue? You can check the "ground truth" by opening the YUV file in a hex editor.

**Comment by 21pages** [comment]
This is the source of png, https://obsproject.com/forum/resources/obs-studio-color-space-color-format-color-range-settings-guide-test-charts.442/

**Comment by 21pages** [comment]
The max hex number in the yuv file is 235, I think I used a  wrong ffmpeg command.

**Comment by ChristianFeldmann** [comment]
Thank you. That looks like some nice test images. So I tooke the image `640x480_color_range_test_chart.png` and used the command you provided on it:
```
ffmpeg -i SomeOriginal.png -pix_fmt yuv420p -sws_flags spline+accurate_rnd+full_chroma_int -color_range 2 -colorspac
e 5 -color_primaries 5 -color_trc 6 -vf scale=800x600 "fullrange_800x600.yuv"
```
The YUV output file that I get has 235 as the highest luma value. So this is a limited range YUV file. YUView also shows this correctly. So I think you are fighting with FFmpeg rather then YUView.

**Comment by ChristianFeldmann** [comment]
Ah commented one second ago. Cool so no bug in YUView. That is good.
