### ISSUE TITLE
Crash every time after open the program on Mac

### ISSUE THREAD

**Issue by smartyoung19** [IENT/YUView#569]
**Describe the bug**
I download the new 2.14 version for mac at github release page. Open the program, it show a update message window. After close the message window, click angwhere of the main window, the program crashed immediately. It happened every time.
I have tried both 2 release version for mac os, the same thing above happened.

**To Reproduce**
1. open the program.
2. an update info window jump out, click OK button.
3. click angwhere of the program main window
4. crash and exist.

**Screenshots**
<img width="1792" alt="image" src="https://github.com/IENT/YUView/assets/87224173/c64a8497-a7b9-450d-b76b-b7ae3461fe11">
<img width="1792" alt="image" src="https://github.com/IENT/YUView/assets/87224173/fc259f3a-d146-4dcb-b1b2-3bed00e2bef0">
<img width="260" alt="image" src="https://github.com/IENT/YUView/assets/87224173/4e5f95e5-fbca-4989-924d-bfb65813761d">

**Version (please complete the following information):**
 - OS: mac os Sonoma 14.4,intel core i7.
 - Version release 2.14

**Comment by ChristianFeldmann** [comment]
Fixed in https://github.com/IENT/YUView/issues/543
Could you test the latest develop branch? It should not happen thhe anymore.

**Comment by smartyoung19** [comment]
OK, thank you. I have tried 2.13 version, it works well. ^_^

**Comment by ChristianFeldmann** [comment]
Ah the older version also works? That was not my suggestion. I thought you could compile and check the latest develop branch version. You can always download the artifacts from the latest develop version here: https://github.com/IENT/YUView/actions/runs/8358910345
