### ISSUE TITLE
please add support for EVC

### ISSUE THREAD

**Issue by i990049** [IENT/YUView#575]
https://github.com/mpeg5
XEVE/XEVD updated recently.

**Comment by ChristianFeldmann** [comment]
Not entirely sure what you mean. What should be supported about EVC? If you have an ffmpeg that can decode EVC then we support this. Or what exactly do you want to work?

**Comment by i990049** [comment]
> Not entirely sure what you mean. What should be supported about EVC? If you have an ffmpeg that can decode EVC then we support this. Or what exactly do you want to work?

https://patchwork.ffmpeg.org/project/ffmpeg/patch/035001d82fc3$bddfd240$399f76c0$@samsung.com/

**Comment by ChristianFeldmann** [comment]
Ok please push that ticket in FFmpeg then. This is not FFmpeg.
