### ISSUE TITLE
yuview crash when open a yuv image, then change format to yuv400 without set width and height(so they are 0)

### ISSUE THREAD

**Issue by shutaozhenzhen** [IENT/YUView#588]
**Describe the bug**
yuview crash when open a yuv image, then change format to yuv400 without set width and height(so they are 0)

**To Reproduce**
1. open a yuv image(new file)
2. change format to yuv400
3. yuview crash

**Expected behavior**
yuview do not crash

**Version (please complete the following information):**
 - OS: Windows 1809
 - Version 2.14
 - If you compiled YUView yourself then which Qt version did you use?

**Comment by for13to1** [comment]
Hi, @shutaozhenzhen 

Can you describe the pixel format, byte size of your YUV file, or just provide it by uploading?
And please reorganize the language to describe the situation when you encountered the bug.
I suppose that YUV400 file can be opened  normally in version 2.14?

**Comment by shutaozhenzhen** [comment]
> Hi, @shutaozhenzhen
> 
> Can you describe the pixel format, byte size of your YUV file, or just provide it by uploading? And please reorganize the language to describe the situation when you encountered the bug. I suppose that YUV400 file can be opened normally in version 2.14?

all file seems can cause this problem.

Just:
1. open a yuv image that do not open before, and can not parse w h format from filename.(So file open as w 0 h 0 format yuv420)
2. do not change w h, directly switch format to yuv400
3. yuview crash

**Comment by ChristianFeldmann** [comment]
This was already fixed on develop. But thanks for the report!
