### ISSUE TITLE
Packet analysis error with libvvdec

### ISSUE THREAD

**Issue by AmirMahmood** [IENT/YUView#590]
Hi. There are many problems with VVC in YUView.
My OS is windows 11 and i use MinGW compiler.
I am using YUView-2.14 and vvdec-2.3.0.
vvdec was compiled as a shared lib with `-DBUILD_SHARED_LIBS=1` flag.
But in packet analyzer there are many errors in NAL units parsing.

And the options for showing Slice Index, Motion vectors and ...  are not available.

Is there any solution? thanks.

![Capture](https://github.com/user-attachments/assets/9cf4ec15-7ec6-43ee-9789-b28647e03f62)

![Screenshot 2024-09-16 021743](https://github.com/user-attachments/assets/b4cadd77-3bf3-4a4d-9a07-7ec486532937)

**Comment by ChristianFeldmann** [comment]
Hi! Thx for the report. 
For the parsing errors, could you make the affected bitstream available to me? This could very well be that there are some bugs for special cases in the parsing code. 
Unfortunately, the vvdec decoder does not support the exposing of data like partitions, motion vector etc. This could definitely be added though.

**Comment by AmirMahmood** [comment]
> Hi! Thx for the report. For the parsing errors, could you make the affected bitstream available to me? This could very well be that there are some bugs for special cases in the parsing code. Unfortunately, the vvdec decoder does not support the exposing of data like partitions, motion vector etc. This could definitely be added though.

OfCourse. this is my bitstream:
[20240906164010_BasketballDrillText_832x480_50.zip](https://github.com/user-attachments/files/17112898/20240906164010_BasketballDrillText_832x480_50.zip)

does libVTM support the exposing of data like partitions and motion vectors?

**Comment by ChristianFeldmann** [comment]
Thx for the file. No unfortunately the libVTM decoder also does not have this. It is straightfoward to add though :)

**Comment by ChristianFeldmann** [comment]
Fixed. The default value for the symbol `sh_collocated_from_l0_flag` was not calculated correctly.
