### ISSUE TITLE
Questionable commit in wiki

### ISSUE THREAD

**Issue by shutaozhenzhen** [IENT/YUView#598]
Two recent commits in the wiki are questionable:
The two commit add link to `https://github.com/EclipseFond/eclipse-collections/releases/download/v2.0.15/AppLauncher-inst-win64.zip` But what is EclipseFond? Why does this software need eclipse?
Even if both commits are correct, it's time to fix the link. Now this link doesn't link to anything

**Comment by ChristianFeldmann** [comment]
Hi! Thx for the report but I am not quite sure which commits you mean. Could you please provide a link to the Wiki pages or the commits?

**Comment by shutaozhenzhen** [comment]
two link on https://github.com/IENT/YUView/wiki/FFmpeg
and one link on https://github.com/IENT/YUView/wiki/Compile-YUView

**Comment by ChristianFeldmann** [comment]
Aah now I see. Thank you so much for the hint. That defninitely looks like something very shady. But the linked files were already taken down by Github. I hope nobody got anything bad with these files. I replaced the links with the real ones and I will check out how they were able to modify the Wiki at all.

**Comment by ChristianFeldmann** [comment]
Looks like by default Wikis on Github can be edited by anybody. That sounds dangerous. I changed that setting.
