### ISSUE TITLE
Tags 2.12 and 2.13 refer to the same commit

### ISSUE THREAD

**Issue by frankplow** [IENT/YUView#603]
Both the v2.12 and v2.13 tags/releases refer to commit a72b395f55f01fe162d549f4ab50222395e6cb3e.  The v.2.13 and v.2.12 tags refer to different commits then their counterpart in the different format.  Not really a major problem for me, but I noticed this and thought I would bring it to your attention if you were not already aware.

**Comment by ChristianFeldmann** [comment]
Thanks for the report. Not sure what happened. But those versions are quire old. I just deleted the 2.12 release and tag. The more up to date 2.12.1 tags and release still exist.
