### ISSUE TITLE
Copy playlist item

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#61]
Would be nice if it would be possible to just copy playlist items. So far if I need anything double, for example to overlay different statistics over the same video I have to open it twice.

**Comment by ChristianFeldmann** [comment]
Maybe we could add the standard Edit->(Copy/Cut/Paste) logic.

**Comment by nolyn** [comment]
that would be great. maybe there is already some support for that in qt,
it's a very common thing after all.

**Comment by KubaO** [comment]
Should be easy to do. I'll look into it.

**Comment by nolyn** [comment]
Addressed by  #347

**Comment by ChristianFeldmann** [comment]
The idea is already really good. I think nobody needs a menu to clone something 20 times. Maybe we just need a context menu to duplicate an item. But I think I would do it a bit differently and also allow for full cloning of the items. 
I started working on this in "feature/61-DuplicateItems" (will push it shortly".

**Comment by ChristianFeldmann** [comment]
Alright I merged a fix for this. Every item in the playlist can now be duplicated. Even containers with all of their properties. This is using the same infrastructure as the saving to playlist. Basically I am saving the item into a temporary playlist and then load it again. While doing this I also fixed some things which were not handled while saving into the playlist.
