### ISSUE TITLE
Class member variable prefixes have a place. 

### ISSUE THREAD

**Issue by KubaO** [IENT/YUView#66]
Currently, we don't want to use class member prefixes for variables. It is suggested that "modern IDEs" remove the need for that.

Yet the reason for them usually isn't to do with IDEs. The major and primary reason is that it makes certain method names impossible to use:

    private:
      int foo;
    public:
      int foo() const; // won't compile
      int getFoo() const; // will compile, but forces a `get` prefix on a public API

When using the `get` prefix on getters, we're making the prefix a part of the API, yet the only need for the prefix is an implementation detail. In Qt, as in the standard library, getters have no prefix. We say `pixmap.size()` or `vector.size()`, not `pixmap.getSize()`.

It's better to have e.g. a private 'm_' member prefix to allow sane member names than to force convoluted public names in the API or member names to avoid clashes. Thus, I suggest we should perhaps prefer this:

    private:
      int m_foo; // private m_prefix
    public:
      int foo() const { return m_foo; }

This issue is a call for discussion only.

**Comment by JensAc** [comment]
I think it is a good idea to have the get prefix, as it is still more conventional to search for getters, if you are new to the code. However modern IDE's will remove the need for that, if it is done by colors, that would not help a colorblind. By the way, the same holds for local variables and members. So, if you ask me, we should stick to the current naming convention and should also use ` this->` in order to make sure that everyone gets the scope of a variable directly.

**Comment by ChristianFeldmann** [comment]
Ok so as far as I see it the two things that we have to decide are:

1. Do we want to use m_ for member variables?
2. Do we use the 'get' prefix for public access functions to member variables?

As @KubaO pointed out, we should choose to use at least one of these options (it would also be possible to use both). Qt uses only option 1.

I browsed a little through stackoverflow but there was no real consens of the 'one good commonly used solution'. However, here is my personal opinion:

- I have no very strong opinion on the matter but I like using only option 2 a little better. For the readability the m_ syntax does not help me a lot. If I am unsure if a variable is a member or not, I just hover the mouse over it an visual studio tells me what it is and where it is defined (for inherited classes it even tells me in what parent class the member is defined in). I also don't mind the get prefix on the getter functions. I even think it is a little clearer when there is a `getSomething()` and `setSomething()` function. 
- I am, however, strongly against @JensAc proposal to use the `this->memberVariable` syntax for every member variable. In my opinnion this just blows up the code and by that makes it less readble.

**Comment by KubaO** [comment]
`this->memberVariable` idea used everywhere is completely non-idiomatic C++ and is horrible.

Alas, my proposal/question has nothing to do with `this->foo` vs `foo` nor with readability. **I'm only commenting about inherent naming clashes that are forbidden by C++**.

For example, suppose we have the following class:

    class Foo {
      int size;
    public:
      int size() const;
    };

This code won't ever compile. It doesn't matter how we name the getter and the member variable: C++ doesn't ever allow them to be named the same.

We should have a "no thinking required" way of fixing the above problem that doesn't look like this:

    class Foo {
      int sz;
    public:
      int size() const { return sz; }
    };

We also don't want to force anyone to name the getter `getSomething`. We need a way to ensure that if someone has a *sensible* name for a member and it clashes with the name of a method, they know how to disambiguate.

I propose that if (and only if) a method **and** a member variable have the same name, the following transformation is applied:

1. The variable is prepended with `m_`.
2. The method name is left unchanged.
3. Corollary: method names beginning with `m_` are not allowed.

That's all. The above transformation shouldn't be IMHO applied when there's no conflict **unless** such conflict was pre-existing and was thus far resolved by breaking the spelling of the member (e.g. `sz` instead of `size` as in example above: it's obvious that `m_size` would be more readable than `sz`).

**Comment by ChristianFeldmann** [comment]
I am cleaning up the issues. This is a very good point but I don't think any action is needed right now.
