### ISSUE TITLE
object files still consuming storage

### ISSUE THREAD

**Issue by JensAc** [IENT/YUView#75]
I observed that there are still coming some quite large object files with cloning.
Packaging for Launchpad will be difficult with those object files, as the whole .git-dir needs to be included in the package for right versioning.

**Comment by ChristianFeldmann** [comment]
When I last checked out the repository it was around 50Mb. Of course the idea is to not have any large object files in the repository. Do you know which files/which branch? Otherwise I could try to look for further unused things/objects.

**Comment by JensAc** [comment]
To be honest I do not know which branches. I simply recognized that the .git/objects/pack consumes the most of the space. I unpacked the object, but that did not help to tackle the issue. I think the size is due to large image and library files in the repository. Maybe, we cannot avoid that. So, is there any solution for making git describe --tags work without having all the older versions in the repo?
![screenshot from 2017-04-01 13-49-16](https://cloud.githubusercontent.com/assets/17930863/24578533/24100a3a-16e2-11e7-9229-3e04df2ee806.png)

**Comment by JensAc** [comment]
Found a solution not having the whole .git dir in the package.

**Comment by ChristianFeldmann** [comment]
I did some investigation and it seems like the most wasted space comes from:
 - old and now unused binraies of libde265
 - Some images that we no longer need
 - An accidental complete commit of generated doxygen files
I think there is some way to retroatively remove these from the repository. I am, however, not yet entirely shure what the consequences of this operation are.
