### ISSUE TITLE
Confusion of playlist items after removing items

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#76]
I haven't been able to figure out how to reproduce this yet, but several times, after I remove an item from the playlist and add another one the buffer of a third item appeared corrupted, displaying not the correct data. After reloading that item it was correct once more. I'll see if I can reproduce it.

**Comment by ChristianFeldmann** [comment]
What do you mean by "not the correct data"? Is another item displayed or the wrong frame? This could be connected to the cache, but it sounds strange becase every item has it's own cache so a mix up between the items should be impossible.
Also in the last update some things related to the loading/caching was changed. Please update first.

**Comment by nolyn** [comment]
yes, I had the impression, that another item was shown. but I couldn't reproduce it intentionally so far. I'll get the update. Maybe it's already fixed

**Comment by ChristianFeldmann** [comment]
A lot changed. Close for now. If this still occurs, please re-open.
