### ISSUE TITLE
"Rate" (fps) seems does not work properly

### ISSUE THREAD

**Issue by drgaliano** [IENT/YUView#80]
Trying to reproduce a video formed by 500 frames with a rate 50 fps, resolution 720 i/p (1280x720) and format "YUV 4:2:0 8-bits", the player takes a lot of time to finish the playback. 
It should take exactly 10 seconds. But takes 23 seconds, more less. It seems that the  system dismiss my configuration.

I detect that when I change the rate to lower values, it takes more time. But, when I assign the correct rate (50 fps) it reproduces about 14 or 16 fps, in the best cases.

Additional information:  

- OS: Mac OS Sierra 10.12.4 (16E195)
- YUView Version: 2.0-64-g45015e9 
￼ - Enabled option: "Caching of video data" to 8683 MB

If you need a video example, do not hesitate to contact with me.

Thanks for your help! Thanks for your work!

**Comment by ChristianFeldmann** [comment]
I heard before that playback on certain versions of Mac OS were slow. However, that was quite some time ago and a lot changed in the code since then. Unfortunately I don't have a Mac to debug this properly. Smaller bugs I can fix on my Mac virtual machine but of course performance tests on a virtual machine are pointless.

**Comment by drgaliano** [comment]
Can I help to you in order to solve this issue? Although I am not programmer expert, maybe I can provide access punctually to my machine to make some tests.

**Comment by ChristianFeldmann** [comment]
Thanks but I might be able to get some access to a mac. I suspect that this is a Qt issue with drawin. Maybe we are saving the cached data in the wrong format so that conversion must occur before every draw operation. I will investigate.

**Comment by ChristianFeldmann** [comment]
Just a short update. On the Mac of a colleague I could observe this behavior using a full HD 420 sequence:
  - Set FPS 20 -> playback at 20
  - Set FPS 30 -> playback at 25
  - Set FPS 40 -> playback at 40
  - Set FPS 50 -> playback at 20
This is definitely not the intended behavior. The drawing itself does not seem to be the bottleneck altough this should be reconfirmed first. Maybe it has something to do with timers and signals/slots on the Mac.

**Comment by ChristianFeldmann** [comment]
I tried to disable the AppNap feature for the app but this did not change the playback behavior. I need to go deeper to find this problem. I need a Mac to build/debug this.

**Comment by ChristianFeldmann** [comment]
We fixed a bug in the QSlider which caused performance issues on Mac. That was possibly it.
