### ISSUE TITLE
Impossibility to close "About" window

### ISSUE THREAD

**Issue by drgaliano** [IENT/YUView#81]
When opening "About YUView", the pop-up has no option to close it.
It is needed to close and reopen the program in order to work properly.

Other information:

* OS: Mac OS Sierra 10.12.4 (16E195)
* YUView Version: 2.0-64-g45015e9

Screenshot attached.
<img width="1680" alt="captura de pantalla 2017-05-04 a las 22 33 50" src="https://cloud.githubusercontent.com/assets/28408499/25723837/f2ae85fa-3119-11e7-997a-bc91c05e60cd.png">

Thanks for all!

**Comment by ChristianFeldmann** [comment]
Thanks for the report. Thies does not seem correct. We are mainly using windows and linux so we can only perform little test on mac.

**Comment by ChristianFeldmann** [comment]
The QTextBrowser with Qt::WindowModal opened a Mac sheet. With Qt::ApplicationModal this does not happen and a seperate window is shown as it is on linux and windows.
Note: I will try to figure out some of the other mac related things before merging this to the main branch and deploying the changes.
