### ISSUE TITLE
Drag and Drop not supported anymore

### ISSUE THREAD

**Issue by aachenmax** [IENT/YUView#82]
Drag and Drop of raw sequences / HEVC streams / statistic files into the playlist instead of opening them manually does not work.

**Comment by ChristianFeldmann** [comment]
For me this works. You have to drop the items on the playlist though. Dropping on the main windo does not work. Is this what you are missing?

**Comment by ChristianFeldmann** [comment]
Ok I'm closing this. If you can reproduce this please feel free to reopen.
