### ISSUE TITLE
ffmpeg path can not be empty once it has been assigned

### ISSUE THREAD

**Issue by drgaliano** [IENT/YUView#83]
If the ffmpeg path is already assigned, you can not change again to empty.
It always requires a path, although you don´t have anymore the ffmpeg library.

In addition, the text field to include the path, it could be good to be free in order to add some hidden paths that usually do not appear in the browser pop-up. For example, the paths "/usr/local/bin" or "/usr/bin" are not be able to be selected with the browsing window.

<img width="533" alt="captura de pantalla 2017-05-05 a las 11 18 43 copia" src="https://cloud.githubusercontent.com/assets/28408499/25740017/ee156cc8-3184-11e7-96f7-f4849509aa3a.png">

**Comment by ChristianFeldmann** [comment]
Fixed. The path can now be edited using the keyboard to anything (also an empty path).
