### ISSUE TITLE
Zooming, panning etc. for secondary display widget

### ISSUE THREAD

**Issue by fjaeger** [IENT/YUView#9]
There are some cases in zooming and panning, which are currently not handled correctly. Especially the behavior when the action is performed in the secondary display widget.
Probably the cleanest approach to compute the corresponding action w.r.t. the primary widget and succeed as if the action was performed there...

**Comment by ChristianFeldmann** [comment]
Okay this is a very old one. The new development branch implementation should handle all of this correctly.
