### ISSUE TITLE
Keep font size when cloning text frames

### ISSUE THREAD

**Issue by nolyn** [IENT/YUView#94]
at the moment, I have to set the size again for each text frame after I cloned it.

**Comment by nolyn** [comment]
would an automatic size adaption make sense, i.e. scaling the text according to the zoom factor of the displayed sequences?

**Comment by ChristianFeldmann** [comment]
Yep the cloning function does not do what it's name suggests. I will take a look into why. I don't understand what you mean with the automatic size adaption. Which sequence? A text item has no connection to any sequence.
