### ISSUE TITLE
Custom YUV format packed selection doesn't stick

### ISSUE THREAD

**Issue by baruchsiach** [IENT/YUView#96]
I have a 1920x1080 raw YUV interleaved file. In the Custom YUV Format dialogue, whenever I choose 4:2:2 Chroma Subsampling,  check the Packed box, and click OK, the YUV Format selection goes back to its previous value. When I open the Custom YUV Format dialogue again, it shows the original values.

I tried both current master (as of commit 194fa1898572a), and the 2.0 release version.

I built on current Debian testing x86-64. Qt version: 5.7.1.

**Comment by ChristianFeldmann** [comment]
Hi and thanks for the report. Could you send me a YUV file with the mentioned format? I can then try to recreated/fix the isssue.

**Comment by baruchsiach** [comment]
How can I send the file? I tried attaching it here but only "known" files type are supported.

**Comment by ChristianFeldmann** [comment]
If you can't host it anywhere, please use the following link: https://gigamove.rz.rwth-aachen.de/u/id/Biea75BVdjAaHB

**Comment by baruchsiach** [comment]
Uploaded. Note that the file is most likely not formatted correctly (got it from and in-development camera sensor interface driver), so don't expect a clear picture. In the best case you would be able to recognize a window with some imagination.

**Comment by ChristianFeldmann** [comment]
I fixed a bug that would reject 422 packed formats as invalid. I can now select the 422 packed format, but the output still looks wrong. Or is this due to the non-alligned sensor interface? Please check the development branch.

**Comment by baruchsiach** [comment]
Thanks for the quick fix. It works now. At least in the sense that the Packed checkbox sticks.

**Comment by ChristianFeldmann** [comment]
I fixed another bug with the packed formats that would display the wrong YUV values when zoomed in. If everything works, we can merge this to the master branch.

**Comment by baruchsiach** [comment]
After rebuild everything still works for me.

Thanks.
